In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"

In [ ]:
import os

print(os.getcwd())

/content

In [ ]:
import os

print(os.listdir("/content/drive/MyDrive"))

['Screenshot_20210721-193715_Chrome.jpg', 'Screenshot_20210720-192752_Chrome.jpg', 'Screenshot_20210720-192409_Chrome.jpg', 'Screenshot_20210720-191917_Chrome.jpg', 'Screenshot_20210717-195403_Chrome.jpg', 'Screenshot_20210717-194604_Chrome.jpg', 'Screenshot_20210715-182504_Chrome.jpg', 'Screenshot_20210709-201505_Chrome.jpg', 'Screenshot_20210708-103432_Chrome.jpg', 'Screen shots ', 'PHYSICS SCREEN SHOTS', 'JEE PREP', 'FIZIKA-2021-Round-I-1.pdf', 'FIZIKA-2021-Round-II.pdf', 'FIZIKA-2021-Round-III.pdf', 'JEE-Main-Maths.pdf', 'Nta papers', 'ORGANIC REAGENTS And Tests.pdf', 'Heat track', 'Classroom', '23BD1A1261_P.jpg', '20231018200741_IMG_9074.JPG', '20231018_170529.jpg', '20231206_132103[1].jpg', 'EXAM FEE .jpg', 'My time', 'Differentiate primary and secondary battery.gdoc', 'Pipe earthing .gdoc', 'Distinguish auto transformer and single phase transformer..gdoc', 'diff between 3 phase and single phase transformer.gsheet', 'Combine both tables.gdoc', 'EDC NOTES_UNIT-2 Part-B(Clippers & Clampers).pdf', 'exam fee 1.jpg', 'Icebreaking best pics', 'comparision between common base, emitter, collect....gdoc', 'Yes i Would you like to explore more complex dict....gdoc', 'Data Structures and Sequences in Python.gdoc', 'Unit 3 Files.gdoc', 'Would you like to delve deeper into\xa0fancy indexing.gdoc', 'error handling in files python.gdoc', 'python', 'WhatsApp Image 2024-08-06 at 01.51.54_ceb02195.jpg', 'Employee certificate.gslides', 'iot_devices.avif', 'connected-devices-internet-of-things-iot-devices.avif', '1', 'Colab Notebooks', 'Maneesh', 'DSC00168.jpg', 'Teachers_day', 'IMG_0982.jpg', 'final_draft', 'what is integrity constraints.gdoc', 'string buffer and string builder in java.gdoc', 'Screenshot_20241121_122952_PhonePe.jpg', 'mudra X aalap', '@the.light_catcher-16.jpg', '@the.light_catcher-17.jpg', '@the.light_catcher-18.jpg', 'FINALL.pptx', 'mve', 'my best friend.gdoc', 'kavya', 'tabula x', 'EDITSSS', 'SAANJH DAY 1 PINK PRASH', 'saanjh dayy2', '_MG_3722.JPG', '_MG_3160.JPG', 'WhatsApp Image 2025-04-29 at 15.20.56_109aee9f.jpg', 'Google AI Studio', 'WhatsApp Image 2025-05-31 at 15.06.16_2a13a017.jpg', 'IMG20250502181623.jpg', '_MG_3160 (1).jpg', 'Students_bulk_sample - Copy.gsheet', 'Personalized Recommendations with Adaptive Learning -AI.pdf', '20250717_190932.heic', 'wonderla', 'Software Requirements Specification (SRS) Document.gdoc', 'pscertificate_0c25991a-f072-462d-ad85-9d9105148ae8.pdf', 'Untitled document.gdoc', 'Plan of Action.pdf', 'Plan of Action.gdoc', 'milestone4', 'Milestone5', 'Screenshot 2025-09-11 195734.png', 'Screenshot 2025-09-11 195817.png', 'Screenshot 2025-09-11 195903.png', 'prjct', 'Milestone 6', 'backend', 'Stock-Market-Consultant-Agent-.pptx', 'Akarshan', 'navraas flashmob_edited', 'trived mudra', '20251004_213443 (1).heic', '20251004_213443.heic', '20251004_213440.heic', 'vaishnavi akka', 'finalll', 'AI-Powered-Cross-Domain-Content-Recommendation-Engine (1).pptx', 'SRS_Group_ID_556.docx', 'Project Report G556.gdoc', 'Screenshot_20251016_133007_PhonePe.jpg', 'IMG_1037-1.jpg', 'Sample', 'ps final', 'gruhapravesham', 'GEN_AI INSULIN DRUG.gdoc', 'GEN_AI INSULIN DRUG.pdf', 'River rafting', 'New_Resume (1).pdf', 'New_Resume.pdf', 'Ipl auction', 'Resume-1.pdf', 'edited', 'resume1_1773241956.pdf', 'Resume', 'dfghj\\', 'photo-gallery.mp4', 'photo-gallery.zip', 'code III unit in python.gdoc', 'DSC_2120 (2).JPG', 'Resume (6).pdf', '1F5D72C1-9DC7-491D-A298-DE4862703683.png', 'Resume (5).pdf', 'Screenshot_20260409_144715_PhonePe.jpg', 'Resume (4).pdf', 'Resume (3).pdf', 'Resume (2).pdf', 'Resume (1).pdf', '20260414_111751 (2).mp4.adding', '20260414_111751 (1).mp4.adding', '20260414_111751.mp4.adding', 'problem.mp4', 'NEHA SAANJH', 'sush', 'kav saanjh', 'Resume.pdf', 'Pramod_sai_resume (1).pdf', 'screenshot.jpeg', 'Resume_Pramod_Sai (5).pdf', 'Resume_Pramod_Sai (4).pdf', 'Resume_Pramod_Sai (3).pdf', 'Resume_Pramod_Sai (2).pdf', 'Resume_Pramod_Sai (1) (1).pdf', 'Resume_Pramod_Sai (1).pdf', 'Pramod_sai_resume.pdf', 'Resume_Pramod_Sai.pdf', 'new (1) (1).pdf', 'new (1).pdf', 'DGCAN_Project', 'resume.pdf']

In [ ]:
print(os.listdir("/content/drive/MyDrive/DGCAN_Project/datasets"))

['raw', 'processed']

In [ ]:
print(os.listdir("/content/drive/MyDrive/DGCAN_Project/datasets/raw"))

['BBBP.csv', 'bace.csv', 'clintox.csv', 'tox21.csv']

LETS GOOOOOOO

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"

In [ ]:
from pathlib import Path

files = sorted(Path(DATASET_PATH).glob("*"))

for file in files:

    print("="*80)
    print(file.name)
    print("="*80)

    if file.suffix == ".csv":
        df = pd.read_csv(file)

    elif file.suffix == ".gz":
        df = pd.read_csv(file, compression="gzip")

    print("Shape :", df.shape)
    print()
    print(df.head())
    print()
    print("Columns:")
    print(df.columns.tolist())
    print("\n")

================================================================================
BBBP.csv
================================================================================
Shape : (2050, 4)

   num                  name  p_np  \
0    1            Propanolol     1
1    2  Terbutylchlorambucil     1
2    3                 40730     1
3    4                    24     1
4    5           cloxacillin     1

                                              smiles
0                   [Cl].CC(C)NCC(O)COc1cccc2ccccc12
1           C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl
2  c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO...
3                   C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C
4  Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)...

Columns:
['num', 'name', 'p_np', 'smiles']


================================================================================
bace.csv
================================================================================
Shape : (1513, 595)

                                                 mol     CID  Class  Model  \
0  O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...  BACE_1      1  Train
1  Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...  BACE_2      1  Train
2  S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...  BACE_3      1  Train
3  S1(=O)(=O)C[C@@H](Cc2cc(O[C@H](COCC)C(F)(F)F)c...  BACE_4      1  Train
4  S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...  BACE_5      1  Train

      pIC50         MW   AlogP  HBA  HBD  RB  ...  PEOE6 (PEOE6)  \
0  9.154901  431.56979  4.4014    3    2   5  ...      53.205711
1  8.853872  657.81073  2.6412    5    4  16  ...      73.817162
2  8.698970  591.74091  2.5499    4    3  11  ...      70.365707
3  8.698970  591.67828  3.1680    4    3  12  ...      56.657166
4  8.698970  629.71283  3.5086    3    3  11  ...      78.945702

   PEOE7 (PEOE7)  PEOE8 (PEOE8)  PEOE9 (PEOE9)  PEOE10 (PEOE10)  \
0      78.640335      226.85541      107.43491        37.133846
1      47.171600      365.67694      174.07675        34.923889
2      47.941147      192.40652      255.75255        23.654478
3      37.954151      194.35304      202.76335        36.498634
4      39.361153      179.71288      220.46130        23.654478

   PEOE11 (PEOE11)  PEOE12 (PEOE12)  PEOE13 (PEOE13)  PEOE14 (PEOE14)  \
0         0.000000         7.980170              0.0         0.000000
1         7.980170        24.148668              0.0        24.663788
2         0.230159        15.879790              0.0        24.663788
3         0.980913         8.188327              0.0        26.385181
4         0.230159        15.879790              0.0        26.100143

   canvasUID
0          1
1          2
2          3
3          4
4          5

[5 rows x 595 columns]

Columns:
['mol', 'CID', 'Class', 'Model', 'pIC50', 'MW', 'AlogP', 'HBA', 'HBD', 'RB', 'HeavyAtomCount', 'ChiralCenterCount', 'ChiralCenterCountAllPossible', 'RingCount', 'PSA', 'Estate', 'MR', 'Polar', 'sLi_Key', 'ssBe_Key', 'ssssBem_Key', 'sBH2_Key', 'ssBH_Key', 'sssB_Key', 'ssssBm_Key', 'sCH3_Key', 'dCH2_Key', 'ssCH2_Key', 'tCH_Key', 'dsCH_Key', 'aaCH_Key', 'sssCH_Key', 'ddC_Key', 'tsC_Key', 'dssC_Key', 'aasC_Key', 'aaaC_Key', 'ssssC_Key', 'sNH3_Key', 'sNH2_Key', 'ssNH2_Key', 'dNH_Key', 'ssNH_Key', 'aaNH_Key', 'tN_Key', 'sssNH_Key', 'dsN_Key', 'aaN_Key', 'sssN_Key', 'ddsN_Key', 'aasN_Key', 'ssssN_Key', 'daaN_Key', 'sOH_Key', 'dO_Key', 'ssO_Key', 'aaO_Key', 'aOm_Key', 'sOm_Key', 'sF_Key', 'sSiH3_Key', 'ssSiH2_Key', 'sssSiH_Key', 'ssssSi_Key', 'sPH2_Key', 'ssPH_Key', 'sssP_Key', 'dsssP_Key', 'ddsP_Key', 'sssssP_Key', 'sSH_Key', 'dS_Key', 'ssS_Key', 'aaS_Key', 'dssS_Key', 'ddssS_Key', 'ssssssS_Key', 'Sm_Key', 'sCl_Key', 'sGeH3_Key', 'ssGeH2_Key', 'sssGeH_Key', 'ssssGe_Key', 'sAsH2_Key', 'ssAsH_Key', 'sssAs_Key', 'dsssAs_Key', 'ddsAs_Key', 'sssssAs_Key', 'sSeH_Key', 'dSe_Key', 'ssSe_Key', 'aaSe_Key', 'dssSe_Key', 'ssssssSe_Key', 'ddssSe_Key', 'sBr_Key', 'sSnH3_Key', 'ssSnH2_Key', 'sssSnH_Key', 'ssssSn_Key', 'sI_Key', 'sPbH3_Key', 'ssPbH2_Key', 'sssPbH_Key', 'ssssPb_Key', 'sLi_Cnt', 'ssBe_Cnt', 'ssssBem_Cnt', 'sBH2_Cnt', 'ssBH_Cnt', 'sssB_Cnt', 'ssssBm_Cnt', 'sCH3_Cnt', 'dCH2_Cnt', 'ssCH2_Cnt', 'tCH_Cnt', 'dsCH_Cnt', 'aaCH_Cnt', 'sssCH_Cnt', 'ddC_Cnt', 'tsC_Cnt', 'dssC_Cnt', 'aasC_Cnt', 'aaaC_Cnt', 'ssssC_Cnt', 'sNH3_Cnt', 'sNH2_Cnt', 'ssNH2_Cnt', 'dNH_Cnt', 'ssNH_Cnt', 'aaNH_Cnt', 'tN_Cnt', 'sssNH_Cnt', 'dsN_Cnt', 'aaN_Cnt', 'sssN_Cnt', 'ddsN_Cnt', 'aasN_Cnt', 'ssssN_Cnt', 'daaN_Cnt', 'sOH_Cnt', 'dO_Cnt', 'ssO_Cnt', 'aaO_Cnt', 'aOm_Cnt', 'sOm_Cnt', 'sF_Cnt', 'sSiH3_Cnt', 'ssSiH2_Cnt', 'sssSiH_Cnt', 'ssssSi_Cnt', 'sPH2_Cnt', 'ssPH_Cnt', 'sssP_Cnt', 'dsssP_Cnt', 'ddsP_Cnt', 'sssssP_Cnt', 'sSH_Cnt', 'dS_Cnt', 'ssS_Cnt', 'aaS_Cnt', 'dssS_Cnt', 'ddssS_Cnt', 'ssssssS_Cnt', 'Sm_Cnt', 'sCl_Cnt', 'sGeH3_Cnt', 'ssGeH2_Cnt', 'sssGeH_Cnt', 'ssssGe_Cnt', 'sAsH2_Cnt', 'ssAsH_Cnt', 'sssAs_Cnt', 'dsssAs_Cnt', 'ddsAs_Cnt', 'sssssAs_Cnt', 'sSeH_Cnt', 'dSe_Cnt', 'ssSe_Cnt', 'aaSe_Cnt', 'dssSe_Cnt', 'ssssssSe_Cnt', 'ddssSe_Cnt', 'sBr_Cnt', 'sSnH3_Cnt', 'ssSnH2_Cnt', 'sssSnH_Cnt', 'ssssSn_Cnt', 'sI_Cnt', 'sPbH3_Cnt', 'ssPbH2_Cnt', 'sssPbH_Cnt', 'ssssPb_Cnt', 'sLi_Sum', 'ssBe_Sum', 'ssssBem_Sum', 'sBH2_Sum', 'ssBH_Sum', 'sssB_Sum', 'ssssBm_Sum', 'sCH3_Sum', 'dCH2_Sum', 'ssCH2_Sum', 'tCH_Sum', 'dsCH_Sum', 'aaCH_Sum', 'sssCH_Sum', 'ddC_Sum', 'tsC_Sum', 'dssC_Sum', 'aasC_Sum', 'aaaC_Sum', 'ssssC_Sum', 'sNH3_Sum', 'sNH2_Sum', 'ssNH2_Sum', 'dNH_Sum', 'ssNH_Sum', 'aaNH_Sum', 'tN_Sum', 'sssNH_Sum', 'dsN_Sum', 'aaN_Sum', 'sssN_Sum', 'ddsN_Sum', 'aasN_Sum', 'ssssN_Sum', 'daaN_Sum', 'sOH_Sum', 'dO_Sum', 'ssO_Sum', 'aaO_Sum', 'aOm_Sum', 'sOm_Sum', 'sF_Sum', 'sSiH3_Sum', 'ssSiH2_Sum', 'sssSiH_Sum', 'ssssSi_Sum', 'sPH2_Sum', 'ssPH_Sum', 'sssP_Sum', 'dsssP_Sum', 'ddsP_Sum', 'sssssP_Sum', 'sSH_Sum', 'dS_Sum', 'ssS_Sum', 'aaS_Sum', 'dssS_Sum', 'ddssS_Sum', 'ssssssS_Sum', 'Sm_Sum', 'sCl_Sum', 'sGeH3_Sum', 'ssGeH2_Sum', 'sssGeH_Sum', 'ssssGe_Sum', 'sAsH2_Sum', 'ssAsH_Sum', 'sssAs_Sum', 'dsssAs_Sum', 'ddsAs_Sum', 'sssssAs_Sum', 'sSeH_Sum', 'dSe_Sum', 'ssSe_Sum', 'aaSe_Sum', 'dssSe_Sum', 'ssssssSe_Sum', 'ddssSe_Sum', 'sBr_Sum', 'sSnH3_Sum', 'ssSnH2_Sum', 'sssSnH_Sum', 'ssssSn_Sum', 'sI_Sum', 'sPbH3_Sum', 'ssPbH2_Sum', 'sssPbH_Sum', 'ssssPb_Sum', 'sLi_Avg', 'ssBe_Avg', 'ssssBem_Avg', 'sBH2_Avg', 'ssBH_Avg', 'sssB_Avg', 'ssssBm_Avg', 'sCH3_Avg', 'dCH2_Avg', 'ssCH2_Avg', 'tCH_Avg', 'dsCH_Avg', 'aaCH_Avg', 'sssCH_Avg', 'ddC_Avg', 'tsC_Avg', 'dssC_Avg', 'aasC_Avg', 'aaaC_Avg', 'ssssC_Avg', 'sNH3_Avg', 'sNH2_Avg', 'ssNH2_Avg', 'dNH_Avg', 'ssNH_Avg', 'aaNH_Avg', 'tN_Avg', 'sssNH_Avg', 'dsN_Avg', 'aaN_Avg', 'sssN_Avg', 'ddsN_Avg', 'aasN_Avg', 'ssssN_Avg', 'daaN_Avg', 'sOH_Avg', 'dO_Avg', 'ssO_Avg', 'aaO_Avg', 'aOm_Avg', 'sOm_Avg', 'sF_Avg', 'sSiH3_Avg', 'ssSiH2_Avg', 'sssSiH_Avg', 'ssssSi_Avg', 'sPH2_Avg', 'ssPH_Avg', 'sssP_Avg', 'dsssP_Avg', 'ddsP_Avg', 'sssssP_Avg', 'sSH_Avg', 'dS_Avg', 'ssS_Avg', 'aaS_Avg', 'dssS_Avg', 'ddssS_Avg', 'ssssssS_Avg', 'Sm_Avg', 'sCl_Avg', 'sGeH3_Avg', 'ssGeH2_Avg', 'sssGeH_Avg', 'ssssGe_Avg', 'sAsH2_Avg', 'ssAsH_Avg', 'sssAs_Avg', 'dsssAs_Avg', 'ddsAs_Avg', 'sssssAs_Avg', 'sSeH_Avg', 'dSe_Avg', 'ssSe_Avg', 'aaSe_Avg', 'dssSe_Avg', 'ssssssSe_Avg', 'ddssSe_Avg', 'sBr_Avg', 'sSnH3_Avg', 'ssSnH2_Avg', 'sssSnH_Avg', 'ssssSn_Avg', 'sI_Avg', 'sPbH3_Avg', 'ssPbH2_Avg', 'sssPbH_Avg', 'ssssPb_Avg', 'First Zagreb (ZM1)', 'First Zagreb index by valence vertex degrees (ZM1V)', 'Second Zagreb (ZM2)', 'Second Zagreb index by valence vertex degrees (ZM2V)', 'Polarity (Pol)', 'Narumi Simple Topological (NST)', 'Narumi Harmonic Topological (NHT)', 'Narumi Geometric Topological (NGT)', 'Total structure connectivity (TSC)', 'Wiener (W)', 'Mean Wiener (MW)', 'Xu (Xu)', 'Quadratic (QIndex)', 'Radial centric (RC)', 'Mean Square Distance Balaban (MSDB)', 'Superpendentic (SP)', 'Harary (Har)', 'Log of product of row sums (LPRS)', 'Pogliani (Pog)', 'Schultz Molecular Topological (SMT)', 'Schultz Molecular Topological by valence vertex degrees (SMTV)', 'Mean Distance Degree Deviation (MDDD)', 'Ramification (Ram)', 'Gutman Molecular Topological (GMT)', 'Gutman MTI by valence vertex degrees (GMTV)', 'Average vertex distance degree (AVDD)', 'Unipolarity (UP)', 'Centralization (CENT)', 'Variation (VAR)', 'Molecular electrotopological variation (MEV)', 'Maximal electrotopological positive variation (MEPV)', 'Maximal electrotopological negative variation (MENV)', 'Eccentric connectivity (ECCc)', 'Eccentricity (ECC)', 'Average eccentricity (AECC)', 'Eccentric (DECC)', 'Valence connectivity index chi-0 (vX0)', 'Valence connectivity index chi-1 (vX1)', 'Valence connectivity index chi-2 (vX2)', 'Valence connectivity index chi-3 (vX3)', 'Valence connectivity index chi-4 (vX4)', 'Valence connectivity index chi-5 (vX5)', 'Average valence connectivity index chi-0 (AvX0)', 'Average valence connectivity index chi-1 (AvX1)', 'Average valence connectivity index chi-2 (AvX2)', 'Average valence connectivity index chi-3 (AvX3)', 'Average valence connectivity index chi-4 (AvX4)', 'Average valence connectivity index chi-5 (AvX5)', 'Quasi Wiener (QW)', 'First Mohar (FM)', 'Second Mohar (SM)', 'Spanning tree number (STN)', 'Kier benzene-likeliness index (KBLI)', 'Topological charge index of order 1 (TCI1)', 'Topological charge index of order 2 (TCI2)', 'Topological charge index of order 3 (TCI3)', 'Topological charge index of order 4 (TCI4)', 'Topological charge index of order 5 (TCI5)', 'Topological charge index of order 6 (TCI6)', 'Topological charge index of order 7 (TCI7)', 'Topological charge index of order 8 (TCI8)', 'Topological charge index of order 9 (TCI9)', 'Topological charge index of order 10 (TCI10)', 'Mean topological charge index of order 1 (MTCI1)', 'Mean topological charge index of order 2 (MTCI2)', 'Mean topological charge index of order 3 (MTCI3)', 'Mean topological charge index of order 4 (MTCI4)', 'Mean topological charge index of order 5 (MTCI5)', 'Mean topological charge index of order 6 (MTCI6)', 'Mean topological charge index of order 7 (MTCI7)', 'Mean topological charge index of order 8 (MTCI8)', 'Mean topological charge index of order 9 (MTCI9)', 'Mean topological charge index of order 10 (MTCI10)', 'Global topological charge (GTC)', 'Hyper-distance-path index (HDPI)', 'Reciprocal hyper-distance-path index (RHDPI)', 'Square reciprocal distance sum (SRDS)', 'Modified Randic connectivity (MRC)', 'Balaban centric (BC)', 'Lopping centric (LC)', 'Kier Hall electronegativity (KHE)', 'Sum of topological distances between N..N (STD(N N))', 'Sum of topological distances between N..O (STD(N O))', 'Sum of topological distances between N..S (STD(N S))', 'Sum of topological distances between N..P (STD(N P))', 'Sum of topological distances between N..F (STD(N F))', 'Sum of topological distances between N..Cl (STD(N Cl))', 'Sum of topological distances between N..Br (STD(N Br))', 'Sum of topological distances between N..I (STD(N I))', 'Sum of topological distances between O..O (STD(O O))', 'Sum of topological distances between O..S (STD(O S))', 'Sum of topological distances between O..P (STD(O P))', 'Sum of topological distances between O..F (STD(O F))', 'Sum of topological distances between O..Cl (STD(O Cl))', 'Sum of topological distances between O..Br (STD(O Br))', 'Sum of topological distances between O..I (STD(O I))', 'Sum of topological distances between S..S (STD(S S))', 'Sum of topological distances between S..P (STD(S P))', 'Sum of topological distances between S..F (STD(S F))', 'Sum of topological distances between S..Cl (STD(S Cl))', 'Sum of topological distances between S..Br (STD(S Br))', 'Sum of topological distances between S..I (STD(S I))', 'Sum of topological distances between P..P (STD(P P))', 'Sum of topological distances between P..F (STD(P F))', 'Sum of topological distances between P..Cl (STD(P Cl))', 'Sum of topological distances between P..Br (STD(P Br))', 'Sum of topological distances between P..I (STD(P I))', 'Sum of topological distances between F..F (STD(F F))', 'Sum of topological distances between F..Cl (STD(F Cl))', 'Sum of topological distances between F..Br (STD(F Br))', 'Sum of topological distances between F..I (STD(F I))', 'Sum of topological distances between Cl..Cl (STD(Cl Cl))', 'Sum of topological distances between Cl..Br (STD(Cl Br))', 'Sum of topological distances between Cl..I (STD(Cl I))', 'Sum of topological distances between Br..Br (STD(Br Br))', 'Sum of topological distances between Br..I (STD(Br I))', 'Sum of topological distances between I..I (STD(I I))', 'Wiener-type index from Z weighted distance matrix - Barysz matrix (WhetZ)', 'Wiener-type index from electronegativity weighted distance matrix (Whete)', 'Wiener-type index from mass weighted distance matrix (Whetm)', 'Wiener-type index from van der waals weighted distance matrix (Whetv)', 'Wiener-type index from polarizability weighted distance matrix (Whetp)', 'Balaban-type index from Z weighted distance matrix - Barysz matrix (JhetZ)', 'Balaban-type index from electronegativity weighted distance matrix (Jhete)', 'Balaban-type index from mass weighted distance matrix (Jhetm)', 'Balaban-type index from van der waals weighted distance matrix (Jhetv)', 'Balaban-type index from polarizability weighted distance matrix (Jhetp)', 'Topological diameter (TD)', 'Topological radius (TR)', 'Petitjean 2D shape (PJ2DS)', 'Balaban distance connectivity index (J)', 'Solvation connectivity index chi-0 (SCIX0)', 'Solvation connectivity index chi-1 (SCIX1)', 'Solvation connectivity index chi-2 (SCIX2)', 'Solvation connectivity index chi-3 (SCIX3)', 'Solvation connectivity index chi-4 (SCIX4)', 'Solvation connectivity index chi-5 (SCIX5)', 'Connectivity index chi-0 (CIX0)', 'Connectivity chi-1 [Randic connectivity] (CIX1)', 'Connectivity index chi-2 (CIX2)', 'Connectivity index chi-3 (CIX3)', 'Connectivity index chi-4 (CIX4)', 'Connectivity index chi-5 (CIX5)', 'Average connectivity index chi-0 (ACIX0)', 'Average connectivity index chi-1 (ACIX1)', 'Average connectivity index chi-2 (ACIX2)', 'Average connectivity index chi-3 (ACIX3)', 'Average connectivity index chi-4 (ACIX4)', 'Average connectivity index chi-5 (ACIX5)', 'reciprocal distance Randic-type index (RDR)', 'reciprocal distance square Randic-type index (RDSR)', '1-path Kier alpha-modified shape index (KAMS1)', '2-path Kier alpha-modified shape index (KAMS2)', '3-path Kier alpha-modified shape index (KAMS3)', 'Kier flexibility (KF)', 'path/walk 2 - Randic shape index (RSIpw2)', 'path/walk 3 - Randic shape index (RSIpw3)', 'path/walk 4 - Randic shape index (RSIpw4)', 'path/walk 5 - Randic shape index (RSIpw5)', 'E-state topological parameter (ETP)', 'Ring Count 3 (RNGCNT3)', 'Ring Count 4 (RNGCNT4)', 'Ring Count 5 (RNGCNT5)', 'Ring Count 6 (RNGCNT6)', 'Ring Count 7 (RNGCNT7)', 'Ring Count 8 (RNGCNT8)', 'Ring Count 9 (RNGCNT9)', 'Ring Count 10 (RNGCNT10)', 'Ring Count 11 (RNGCNT11)', 'Ring Count 12 (RNGCNT12)', 'Ring Count 13 (RNGCNT13)', 'Ring Count 14 (RNGCNT14)', 'Ring Count 15 (RNGCNT15)', 'Ring Count 16 (RNGCNT16)', 'Ring Count 17 (RNGCNT17)', 'Ring Count 18 (RNGCNT18)', 'Ring Count 19 (RNGCNT19)', 'Ring Count 20 (RNGCNT20)', 'Atom Count (ATMCNT)', 'Bond Count (BNDCNT)', 'Atoms in Ring System (ATMRNGCNT)', 'Bonds in Ring System (BNDRNGCNT)', 'Cyclomatic number (CYCLONUM)', 'Number of ring systems (NRS)', 'Normalized number of ring systems (NNRS)', 'Ring Fusion degree (RFD)', 'Ring perimeter (RNGPERM)', 'Ring bridge count (RNGBDGE)', 'Molecule cyclized degree (MCD)', 'Ring Fusion density (RFDELTA)', 'Ring complexity index (RCI)', 'Van der Waals surface area (VSA)', 'MR1 (MR1)', 'MR2 (MR2)', 'MR3 (MR3)', 'MR4 (MR4)', 'MR5 (MR5)', 'MR6 (MR6)', 'MR7 (MR7)', 'MR8 (MR8)', 'ALOGP1 (ALOGP1)', 'ALOGP2 (ALOGP2)', 'ALOGP3 (ALOGP3)', 'ALOGP4 (ALOGP4)', 'ALOGP5 (ALOGP5)', 'ALOGP6 (ALOGP6)', 'ALOGP7 (ALOGP7)', 'ALOGP8 (ALOGP8)', 'ALOGP9 (ALOGP9)', 'ALOGP10 (ALOGP10)', 'PEOE1 (PEOE1)', 'PEOE2 (PEOE2)', 'PEOE3 (PEOE3)', 'PEOE4 (PEOE4)', 'PEOE5 (PEOE5)', 'PEOE6 (PEOE6)', 'PEOE7 (PEOE7)', 'PEOE8 (PEOE8)', 'PEOE9 (PEOE9)', 'PEOE10 (PEOE10)', 'PEOE11 (PEOE11)', 'PEOE12 (PEOE12)', 'PEOE13 (PEOE13)', 'PEOE14 (PEOE14)', 'canvasUID']


================================================================================
clintox.csv
================================================================================
Shape : (1484, 3)

                                              smiles  FDA_APPROVED  CT_TOX
0            *C(=O)[C@H](CCCCNC(=O)OCCOC)NC(=O)OCCOC             1       0
1  [C@@H]1([C@@H]([C@@H]([C@H]([C@@H]([C@@H]1Cl)C...             1       0
2  [C@H]([C@@H]([C@@H](C(=O)[O-])O)O)([C@H](C(=O)...             1       0
3  [H]/[NH+]=C(/C1=CC(=O)/C(=C\C=c2ccc(=C([NH3+])...             1       0
4  [H]/[NH+]=C(\N)/c1ccc(cc1)OCCCCCOc2ccc(cc2)/C(...             1       0

Columns:
['smiles', 'FDA_APPROVED', 'CT_TOX']


================================================================================
tox21.csv
================================================================================
Shape : (7831, 14)

   NR-AR  NR-AR-LBD  NR-AhR  NR-Aromatase  NR-ER  NR-ER-LBD  NR-PPAR-gamma  \
0    0.0        0.0     1.0           NaN    NaN        0.0            0.0
1    0.0        0.0     0.0           0.0    0.0        0.0            0.0
2    NaN        NaN     NaN           NaN    NaN        NaN            NaN
3    0.0        0.0     0.0           0.0    0.0        0.0            0.0
4    0.0        0.0     0.0           0.0    0.0        0.0            0.0

   SR-ARE  SR-ATAD5  SR-HSE  SR-MMP  SR-p53    mol_id  \
0     1.0       0.0     0.0     0.0     0.0   TOX3021
1     NaN       0.0     NaN     0.0     0.0   TOX3020
2     0.0       NaN     0.0     NaN     NaN   TOX3024
3     NaN       0.0     NaN     0.0     0.0   TOX3027
4     0.0       0.0     0.0     0.0     0.0  TOX20800

                                              smiles
0                       CCOc1ccc2nc(S(N)(=O)=O)sc2c1
1                          CCN1C(=O)NC(c2ccccc2)C1=O
2  CC[C@]1(O)CC[C@H]2[C@@H]3CCC4=CCCC[C@@H]4[C@H]...
3                    CCCN(CC)C(CC)C(=O)Nc1c(C)cccc1C
4                          CC(O)(P(=O)(O)O)P(=O)(O)O

Columns:
['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD', 'NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53', 'mol_id', 'smiles']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!git clone https://github.com/JinYSun/D-GCAN.git

Cloning into 'D-GCAN'...
remote: Enumerating objects: 493, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 493 (delta 31), reused 30 (delta 14), pack-reused 441 (from 1)
Receiving objects: 100% (493/493), 7.53 MiB | 17.64 MiB/s, done.
Resolving deltas: 100% (278/278), done.

In [ ]:
%cd D-GCAN/DGCAN

/content/D-GCAN/DGCAN

In [ ]:
!pip -q install rdkit-pypi
!pip -q install networkx
!pip -q install scipy
!pip -q install pandas
!pip -q install numpy
!pip -q install scikit-learn
!pip -q install matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 84.4 MB/s eta 0:00:00

In [ ]:
import torch
import pandas as pd
import numpy as np

print(torch.__version__)
print(pd.__version__)

2.6.0+cu124
2.2.2

In [ ]:
%cd D-GCAN/DGCAN

[Errno 2] No such file or directory: 'D-GCAN/DGCAN'
/content/D-GCAN/DGCAN

In [ ]:
import os
print(os.getcwd())

/content/D-GCAN/DGCAN

In [ ]:
!ls

DGCAN.py  __init__.py  preprocess.py  run.py	Tutorial.ipynb
dict	  predict.py   results	      train.py

In [ ]:
import preprocess as pp

print("Imported Successfully")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-20-1411732915.py", line 1, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/usr/local/lib/python3.11/dist-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-20-1411732915.py", line 1, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 20, in <module>
    from rdkit.Chem import rdchem

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-20-1411732915.py", line 1, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 24, in <module>
    from rdkit.Chem.rdmolops import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-20-1411732915.py", line 1, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 20, in <module>
    from rdkit.Chem import rdDepictor

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-20-1411732915.py", line 1, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 21, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D

AttributeError: _ARRAY_API not found

Imported Successfully

In [ ]:
import sys
print(sys.version)

3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]

In [ ]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.3-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from rdkit) (11.2.1)
Downloading rdkit-2026.3.3-cp311-cp311-manylinux_2_28_x86_64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 43.7 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.3

In [ ]:
import preprocess as pp

print("DGCAN Imported Successfully ✅")

DGCAN Imported Successfully ✅

In [ ]:
%cd D-GCAN/DGCAN

[Errno 2] No such file or directory: 'D-GCAN/DGCAN'
/content/D-GCAN/DGCAN

In [ ]:
!git clone https://github.com/JinYSun/D-GCAN.git

fatal: destination path 'D-GCAN' already exists and is not an empty directory.

In [ ]:
%cd D-GCAN/DGCAN

/content/D-GCAN/DGCAN

In [ ]:
from rdkit import Chem

print("RDKit Installed Successfully ✅")

RDKit Installed Successfully ✅

In [ ]:
import preprocess as pp

print("DGCAN Imported Successfully ✅")

DGCAN Imported Successfully ✅

In [ ]:
!nvidia-smi

Mon Jul  6 18:08:45 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1

In [ ]:
print(torch.cuda.get_device_name(0))

Tesla T4

In [ ]:
!nvidia-smi

Mon Jul  6 18:08:45 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8             13W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
import torch

print("CUDA Available:", torch.cuda.is_available())
print("CUDA Version:", torch.version.cuda)
print("GPU Count:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA Available: True
CUDA Version: 12.4
GPU Count: 1
GPU: Tesla T4

In [ ]:
!grep -n "def create_dataset" preprocess.py

157:def create_dataset(filename,path,dataname):

In [ ]:
!sed -n '157,260p' preprocess.py

def create_dataset(filename,path,dataname):
    dir_dataset = path+dataname
    print(filename)
    """Load a dataset."""
    try:
        with open(dir_dataset + filename, 'r') as f:
            smiles_property = f.readline().strip().split()
            data_original = f.read().strip().split('\n')
    except:
        with open(dir_dataset + filename, 'r') as f:
            smiles_property = f.readline().strip().split()
            data_original = f.read().strip().split('\n')

        """Exclude the data contains '.' in its smiles.排除含.的数据"""
    data_original = [data for data in data_original
                        if '.' not in data.split()[0]]
    dataset = []
    for data in data_original:
            smiles, property = data.strip().split()
            try:
                """Create each data with the above defined functions."""
                mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
                atoms = create_atoms(mol, atom_dict)
                molecular_size = len(atoms)
                i_jbond_dict = create_ijbonddict(mol, bond_dict)
                fingerprints = extract_fingerprints(radius, atoms, i_jbond_dict,
                                                    fingerprint_dict, edge_dict)
                adjacency = Chem.GetAdjacencyMatrix(mol)
                """
                Transform the above each data of numpy
                to pytorch tensor on a device (i.e., CPU or GPU).
                """
                fingerprints = torch.LongTensor(fingerprints).to(device)
                adjacency = torch.FloatTensor(adjacency).to(device)
                property = torch.LongTensor([int(property)]).to(device)
                dataset.append((smiles,fingerprints, adjacency, molecular_size, property))
            except:
                print(smiles)
    return dataset

In [ ]:
!head -20 ../dataset/bRo5.txt

CC1=NC=C(N=C1)C(=O)NCCC1=CC=C(C=C1)S(=O)(=O)NC(=O)NC1CCCCC1	1
CN1CCN(CC1)C(=O)O[C@@H]1N(C(=O)C2=NC=CN=C12)C1=NC=C(Cl)C=C1	1
[H][C@@]12CCO[C@]1([H])OC[C@@H]2OC(=O)N[C@@H](CC1=CC=CC=C1)[C@H](O)CN(CC(C)C)S(=O)(=O)C1=CC=C(N)C=C1	1
COC1=C(OC)C=C2[C@@H](CN(C)CCCN3CCC4=CC(OC)=C(OC)C=C4CC3=O)CC2=C1	1
[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)[C@H](C(O)=O)C1=CSC=C1)C(O)=O	1
CC[N+](C)(CC)CCOC(=O)C1C2=CC=CC=C2OC2=CC=CC=C12	1
CC(C)O	1
COC1=CC2=C(NC(=N2)[S@@](=O)CC2=NC=C(C)C(OC)=C2C)C=C1	1
COC1=C(OC)C=C2C(N)=NC(=NC2=C1)N1CCN(CC1)C(=O)C1CCCO1	1
CCCCC(=O)N(CC1=CC=C(C=C1)C1=CC=CC=C1C1=NNN=N1)[C@@H](C(C)C)C(O)=O	1
CN(CCCCCCCCCCN(C)C(=O)OC1=CC=CC(=C1)[N+](C)(C)C)C(=O)OC1=CC=CC(=C1)[N+](C)(C)C	1
NC[C@H](O)C1=CC(O)=C(O)C=C1	1
C[N+]1(C)CCC(C1)OC(=O)C(O)(C1CCCC1)C1=CC=CC=C1	1
CCC1(CCC(=O)NC1=O)C1=CC=CC=C1	1
OCC(O)COC1=CC=C(Cl)C=C1	1
O=[N+]([O-])c1cc([N+](=O)[O-])c(O)c([N+](=O)[O-])c1	1
NC1=NC(=O)C2=C(N1)N(CCC(CO)CO)C=N2	1
CC1=CC(CN2CCC(CC2)=C2C3=CC=C(Cl)C=C3CCC3=C2N=CC=C3)=CN=C1	1
CSCCNC1=C2N=CN([C@@H]3O[C@H](COP(O)(=O)OP(O)(=O)C(Cl)(Cl)P(O)(O)=O)[C@@H](O)[C@H]3O)C2=NC(SCCC(F)(F)F)=N1	1
CCC(C1=CC=CC=C1)C1=C(O)C2=C(OC1=O)C=CC=C2	1

In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
def convert_dataset(csv_path, smiles_col, label_col, output_path):
    """
    Convert a MoleculeNet CSV dataset into the D-GCAN text format.
    """

    # Read dataset
    df = pd.read_csv(csv_path)

    print(f"Original Shape: {df.shape}")

    df = df[[smiles_col, label_col]]

    df = df.dropna()

    df = df.drop_duplicates(subset=[smiles_col])

    # Remove disconnected molecules
    df = df[~df[smiles_col].str.contains(r"\.")]

    df[label_col] = df[label_col].astype(int)

    with open(output_path, "w") as f:
      for _, row in df.iterrows():
        f.write(f"{row[smiles_col]}\t{row[label_col]}\n")
    print(f"\nSaved to:\n{output_path}")

In [ ]:
RAW = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"
PROCESSED = "/content/drive/MyDrive/DGCAN_Project/datasets/processed"

Path(PROCESSED).mkdir(parents=True, exist_ok=True)

convert_dataset(
    csv_path=f"{RAW}/BBBP.csv",
    smiles_col="smiles",
    label_col="p_np",
    output_path=f"{PROCESSED}/BBBP.txt"
)

Original Shape: (2050, 4)

Saved to:
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP.txt

In [ ]:
with open(f"{PROCESSED}/BBBP.txt") as f:

    for _ in range(10):
        print(f.readline().strip())

C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl	1
c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO3)=O	1
C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C	1
Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)[C@@H](N4C3=O)C(O)=O	1
CCN1CCN(C(=O)N[C@@H](C(=O)N[C@H]2[C@H]3SCC(=C(N3C2=O)C(O)=O)CSc4nnnn4C)c5ccc(O)cc5)C(=O)C1=O	1
CN(C)[C@H]1[C@@H]2C[C@H]3C(=C(O)c4c(O)cccc4[C@@]3(C)O)C(=O)[C@]2(O)C(=O)\C(=C(/O)NCN5CCCC5)C1=O	1
Cn1c2CCC(Cn3ccnc3C)C(=O)c2c4ccccc14	1
COc1ccc(cc1)[C@@H]2Sc3ccccc3N(CCN(C)C)C(=O)[C@@H]2OC(C)=O	1
NC(N)=NC(=O)c1nc(Cl)c(N)nc1N	1
OCC(C)(O)c1onc(c2ncn3c2CN(C)C(c4c3cccc4Cl)=O)n1	0

In [ ]:
with open("../dataset/bRo5.txt") as f:
    print("Original Header :", repr(f.readline()))
    print("Original First Row :", repr(f.readline()))

print()

with open("/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP.txt") as f:
    print("BBBP Header :", repr(f.readline()))
    print("BBBP First Row :", repr(f.readline()))

Original Header : 'CC1=NC=C(N=C1)C(=O)NCCC1=CC=C(C=C1)S(=O)(=O)NC(=O)NC1CCCCC1\t1\n'
Original First Row : 'CN1CCN(CC1)C(=O)O[C@@H]1N(C(=O)C2=NC=CN=C12)C1=NC=C(Cl)C=C1\t1\n'

BBBP Header : 'C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl\t1\n'
BBBP First Row : 'c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO3)=O\t1\n'

In [ ]:
import preprocess as pp

dataset_bbbp = pp.create_dataset(
    "BBBP.txt",
    "/content/drive/MyDrive/DGCAN_Project/datasets/",
    "processed/"
)

print("Dataset Size:", len(dataset_bbbp))
print(type(dataset_bbbp[0]))

In [ ]:
sample = dataset_bbbp[0]

print("SMILES:", sample[0])
print("Fingerprint shape:", sample[1].shape)
print("Adjacency shape:", sample[2].shape)
print("Molecular size:", sample[3])
print("Label:", sample[4])

In [ ]:
!pip install -q deepchem

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 60.4 MB/s eta 0:00:00

In [ ]:
import deepchem as dc
print(dc.__version__)

WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for SPS. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for AvgIpc. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumAmideBonds. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumAtomStereoCenters. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumBridgeheadAtoms. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumHeterocycles. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumSpiroAtoms. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
WARNING:deepchem.feat.molecule_featurizers.rdkit_descriptors:No normalization for Phi. Feature removed!
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
WARNING:tensorflow:From /usr/local/lib/python3.11/dist-packages/tensorflow/python/util/deprecation.py:588: calling function (from tensorflow.python.eager.polymorphic_function.polymorphic_function) with experimental_relax_shapes is deprecated and will be removed in a future version.
Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
WARNING:deepchem.models.torch_models:Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
WARNING:deepchem.models:Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/usr/local/lib/python3.11/dist-packages/deepchem/models/torch_models/__init__.py)
WARNING:deepchem.models:Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
WARNING:deepchem.models:Skipped loading some Jax models, missing a dependency. No module named 'haiku'

2.8.0

In [ ]:
import pandas as pd
import deepchem as dc
from pathlib import Path

In [ ]:
RAW = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"

df = pd.read_csv(f"{RAW}/BBBP.csv")

print(df.shape)

df.head()

(2050, 4)

,num,name,p_np,smiles
0,1,Propanolol,1,[Cl].CC(C)NCC(O)COc1cccc2ccccc12
1,2,Terbutylchlorambucil,1,C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl
2,3,40730,1,c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO...
3,4,24,1,C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C
4,5,cloxacillin,1,Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)...

In [ ]:
df = df[["smiles", "p_np"]]

df = df.dropna()

df = df.drop_duplicates(subset=["smiles"])

df = df[~df["smiles"].str.contains(r"\.")]

df["p_np"] = df["p_np"].astype(int)

print(df.shape)

(1945, 2)

In [ ]:
dataset = dc.data.NumpyDataset(
    X=df["smiles"].values,
    y=df["p_np"].values,
    ids=df["smiles"].values
)

In [ ]:
splitter = dc.splits.ScaffoldSplitter()

train, valid, test = splitter.train_valid_test_split(
    dataset,
    frac_train=0.8,
    frac_valid=0.1,
    frac_test=0.1,
    seed=42
)

[18:11:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[18:11:35] Explicit valence for atom # 5 N, 4, is greater than permitted

In [ ]:
print("Train :", len(train))
print("Valid :", len(valid))
print("Test  :", len(test))

Train : 1556
Valid : 194
Test  : 184

In [ ]:
from pathlib import Path

PROCESSED = "/content/drive/MyDrive/DGCAN_Project/datasets/processed"

Path(PROCESSED).mkdir(parents=True, exist_ok=True)


def save_split(dataset, filename):
    with open(f"{PROCESSED}/{filename}", "w") as f:
        for smiles, label in zip(dataset.ids, dataset.y):
            f.write(f"{smiles}\t{int(label)}\n")

    print(f"Saved {filename} ({len(dataset)} molecules)")

In [ ]:
save_split(train, "BBBP_train.txt")
save_split(valid, "BBBP_valid.txt")
save_split(test, "BBBP_test.txt")

Saved BBBP_train.txt (1556 molecules)
Saved BBBP_valid.txt (194 molecules)
Saved BBBP_test.txt (184 molecules)

In [ ]:
!head -5 /content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt

C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl	1
C[C@H](N)Cc1ccccc1	1
C[S](=O)(=O)c1ccc(cc1)[C@@H](O)[C@@H](CO)NC(=O)C(Cl)Cl	1
CC(N)COc1c(C)cccc1C	1
c1(ccccc1)CC	1

In [ ]:
!grep -n "create_dataset" train.py

100:    dataset_train=   pp.create_dataset(dataset_train,path,dataname)
102:    #dataset_test=   pp.create_dataset(dataset_dev,path,dataname)
103:    dataset_test= pp.create_dataset(dataset_test,path,dataname)

In [ ]:
!sed -n '70,150p' train.py

    dataset_train='../dataset/data_train.txt') #training set

    Returns
    -------
    res_test : results
        Predicting results.

    '''
    dataset_test = test_name
    (radius, dim, layer_hidden, layer_output,
     batch_train, batch_test, decay_interval,
     iteration, dropout) = map(int, [radius, dim, layer_hidden, layer_output,
                                     batch_train, batch_test,
                                     decay_interval, iteration, dropout])
    lr, lr_decay = map(float, [lr, lr_decay])
    if torch.cuda.is_available():
        device = torch.device('cuda')
        print('The code uses a GPU!')
    else:
        device = torch.device('cpu')
        print('The code uses a CPU...')

    lr, lr_decay = map(float, [lr, lr_decay])

    print('-' * 100)
    print('Just a moment......')
    print('-' * 100)
    path = ''
    dataname = ''

    dataset_train=   pp.create_dataset(dataset_train,path,dataname)
    #dataset_train,dataset_test = pp.split_dataset(dataset_train,0.9)
    #dataset_test=   pp.create_dataset(dataset_dev,path,dataname)
    dataset_test= pp.create_dataset(dataset_test,path,dataname)
    np.random.seed(0)
    np.random.shuffle(dataset_train)
    print('The preprocess has finished!')
    print('-' * 100)

    print('Creating a model.')
    torch.manual_seed(0)
    model = MolecularGraphNeuralNetwork(
        N, dim, layer_hidden, layer_output, dropout).to(device)
    trainer = Trainer(model,lr,batch_train)
    tester = Tester(model,batch_test)
    print('# of model parameters:',
          sum([np.prod(p.size()) for p in model.parameters()]))
    print('-' * 100)
    file_result = path + '../DGCAN/results/AUC' + '.txt'
    #    file_result = '../output/result--' + setting + '.txt'
    result = 'Epoch\tTime(sec)\tLoss_train\tLoss_test\tAUC_train\tAUC_test'
    file_test_result = path + 'test_prediction' + '.txt'
    file_predictions = path + 'train_prediction' + '.txt'
    file_model = '../DGCAN/model/model' + '.pth'
    with open(file_result, 'w') as f:
        f.write(result + '\n')

    print('Start training.')
    print('The result is saved in the output directory every epoch!')

    np.random.seed(0)

    start = timeit.default_timer()

    for epoch in range(iteration):
        epoch += 1
        if epoch % decay_interval == 0:
            trainer.optimizer.param_groups[0]['lr'] *= lr_decay
        # [‘amsgrad’, ‘params’, ‘lr’, ‘betas’, ‘weight_decay’, ‘eps’]
        prediction_train, loss_train, train_res = trainer.train(dataset_train)
        prediction_test, loss_test, test_res = tester.test_classifier(dataset_test)

        time = timeit.default_timer() - start

        if epoch == 1:
            minutes = time * iteration / 60
            hours = int(minutes / 60)
            minutes = int(minutes - 60 * hours)
            print('The training will finish in about',
                  hours, 'hours', minutes, 'minutes.')
            print('-' * 100)

In [ ]:
!grep -n "train(" run.py

19:tes = train.train('../dataset/data_test.txt',

In [ ]:
!grep -n "^def train" train.py

51:def train (test_name, radius, dim, layer_hidden, layer_output, dropout, batch_train,

In [ ]:
!sed -n '1,70p' train.py

# -*- coding: utf-8 -*-
"""
Created on Wed Apr 27 20:09:31 2022

@author:Jinyu-Sun
"""

import timeit
import sys
import numpy as np
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pickle
from sklearn.metrics import roc_auc_score, roc_curve,auc
from sklearn.metrics import confusion_matrix
import preprocess as pp
import pandas as pd
import matplotlib.pyplot as plt
from DGCAN import MolecularGraphNeuralNetwork,Trainer,Tester

def metrics(cnf_matrix):
    '''Evaluation Metrics'''
    tn = cnf_matrix[0, 0]
    tp = cnf_matrix[1, 1]
    fn = cnf_matrix[1, 0]
    fp = cnf_matrix[0, 1]

    bacc = ((tp / (tp + fn)) + (tn / (tn + fp))) / 2  # balance accurance
    pre = tp / (tp + fp)  # precision/q+
    rec = tp / (tp + fn)  # recall/se
    sp = tn / (tn + fp)
    q_ = tn / (tn + fn)
    f1 = 2 * pre * rec / (pre + rec)  # f1score
    mcc = ((tp * tn) - (fp * fn)) / math.sqrt(
        (tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))  # Matthews correlation coefficient
    acc = (tp + tn) / (tp + fp + fn + tn)  # accurancy

    print('bacc:', bacc)
    print('pre:', pre)
    print('rec:', rec)
    print('f1:', f1)
    print('mcc:', mcc)
    print('sp:', sp)
    print('q_:', q_)
    print('acc:', acc)


def train (test_name, radius, dim, layer_hidden, layer_output, dropout, batch_train,
    batch_test, lr, lr_decay, decay_interval, iteration, N , dataset_train):
    '''

    Parameters
    ----------
    data_test='../dataset/data_test.txt', #test set
    radius = 1,        #hops of radius subgraph: 1, 2
    dim = 64,          #dimension of graph convolution layers
    layer_hidden = 4,  #Number of graph convolution layers
    layer_output = 10, #Number of dense layers
    dropout = 0.45,    #drop out rate :0-1
    batch_train = 8,   # batch of training set
    batch_test = 8,    #batch of test set
    lr =3e-4,          #learning rate: 1e-5,1e-4,3e-4, 5e-4, 1e-3, 3e-3,5e-3
    lr_decay = 0.85,   #Learning rate decay:0.5, 0.75, 0.85, 0.9
    decay_interval = 25,#Number of iterations for learning rate decay:10,25,30,50
    iteration = 140,    #Number of iterations
    N = 5000,           #length of embedding: 2000,3000,5000,7000
    dataset_train='../dataset/data_train.txt') #training set

THE ACTUAL OUR TRAINING START HERE
BELOW WE ARE BACKING UP THE TRAINING CODE

In [ ]:
!cp /content/D-GCAN/DGCAN/train.py /content/D-GCAN/DGCAN/train_original.py

print("✅ Backup created: train_original.py")

✅ Backup created: train_original.py

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/train.py")

text = train_file.read_text()

old = """def train (test_name, radius, dim, layer_hidden, layer_output, dropout, batch_train,
    batch_test, lr, lr_decay, decay_interval, iteration, N , dataset_train):"""

new = """def train (test_name, valid_name, radius, dim, layer_hidden, layer_output, dropout, batch_train,
    batch_test, lr, lr_decay, decay_interval, iteration, N , dataset_train):"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ Added valid_name parameter")

✅ Added valid_name parameter

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/train.py")

text = train_file.read_text()

old = """    dataset_train=   pp.create_dataset(dataset_train,path,dataname)
    #dataset_train,dataset_test = pp.split_dataset(dataset_train,0.9)
    #dataset_test=   pp.create_dataset(dataset_dev,path,dataname)
    dataset_test= pp.create_dataset(dataset_test,path,dataname)"""

new = """    dataset_train = pp.create_dataset(dataset_train, path, dataname)

    dataset_valid = pp.create_dataset(valid_name, path, dataname)

    dataset_test = pp.create_dataset(dataset_test, path, dataname)"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ Validation dataset added")

✅ Validation dataset added

In [ ]:
!grep -n "def train" /content/D-GCAN/DGCAN/train.py

51:def train (test_name, valid_name, radius, dim, layer_hidden, layer_output, dropout, batch_train,

In [ ]:
!grep -n "dataset_valid" /content/D-GCAN/DGCAN/train.py

102:    dataset_valid = pp.create_dataset(valid_name, path, dataname)

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/train.py")

text = train_file.read_text()

old = """        prediction_train, loss_train, train_res = trainer.train(dataset_train)
        prediction_test, loss_test, test_res = tester.test_classifier(dataset_test)"""

new = """        prediction_train, loss_train, train_res = trainer.train(dataset_train)
        prediction_valid, loss_valid, valid_res = tester.test_classifier(dataset_valid)"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ Validation evaluation added")

✅ Validation evaluation added

In [ ]:
!grep -n "prediction_valid" /content/D-GCAN/DGCAN/train.py

141:        prediction_valid, loss_valid, valid_res = tester.test_classifier(dataset_valid)

In [ ]:
!grep -n "def test_classifier" /content/D-GCAN/DGCAN/DGCAN.py

227:    def test_classifier(self, dataset):

In [ ]:
!sed -n '227,340p' /content/D-GCAN/DGCAN/DGCAN.py

    def test_classifier(self, dataset):
        N = len(dataset)
        loss_total = 0
        SMILES, P, C = '', [], []
        for i in range(0, N, self.batch_test):
            data_batch = list(zip(*dataset[i:i + self.batch_test]))
            (Smiles, loss, predicted_scores, correct_labels) = self.model.forward_classifier(
                data_batch, train=False)
            SMILES += ' '.join(Smiles) + ' '
            loss_total += loss.item()
            P.append(predicted_scores)
            C.append(correct_labels)
        SMILES = SMILES.strip().split()
        tru = np.concatenate(C)
        pre = np.concatenate(P)
        pred = [1 if i >0.15 else 0 for i in pre]
        #AUC = roc_auc_score(tru, pre)
        cnf_matrix=confusion_matrix(tru,pred)
        tn = cnf_matrix[0, 0]
        tp = cnf_matrix[1, 1]
        fn = cnf_matrix[1, 0]
        fp = cnf_matrix[0, 1]
        acc = (tp + tn) / (tp + fp + fn + tn)
        #  Tru=map(str,np.concatenate(C))
        #  Pre=map(str,np.concatenate(P))
        #  predictions = '\n'.join(['\t'.join(x) for x in zip(SMILES, Tru, Pre)])
        predictions = np.stack((tru, pred, pre))
        return acc, loss_total, predictions

    def save_result(self, result, filename):
        with open(filename, 'a') as f:
            f.write(result + '\n')

    def save_predictions(self, predictions, filename):
        with open(filename, 'w') as f:
            f.write('Smiles\tCorrect\tPredict\n')
            f.write(predictions + '\n')

    def save_model(self, model, filename):
        torch.save(model.state_dict(), filename)

def dump_dictionary(dictionary, filename):
    with open('../DGCAN/model'+filename, 'wb') as f:
        pickle.dump(dict(dictionary), f)

In [ ]:
!sed -n '341,400p' /content/D-GCAN/DGCAN/DGCAN.py

HERE WE FOUND A GOOD OBSERVATION THAT                                        The original paper doesn't even use AUC for model selection.It returns:

acc

instead of

AUC

Yet the paper reports AUC.

Even worse,

pred = [1 if i > 0.15 else 0 for i in pre]

The threshold is hardcoded to 0.15.

Remember?

Months ago we discovered this exact thing while reproducing D-GCAN.

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/DGCAN.py")

text = train_file.read_text()

old = """        #AUC = roc_auc_score(tru, pre)
        cnf_matrix=confusion_matrix(tru,pred)
"""

new = """        AUC = roc_auc_score(tru, pre)
        cnf_matrix=confusion_matrix(tru,pred)
"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ AUC computation added")

✅ AUC computation added

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/DGCAN.py")

text = train_file.read_text()

old = """        return acc, loss_total, predictions"""

new = """        return {
            "auc": AUC,
            "acc": acc
        }, loss_total, predictions"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ Metrics dictionary added")

✅ Metrics dictionary added

In [ ]:
!grep -n "return {" /content/D-GCAN/DGCAN/DGCAN.py

254:        return {

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/train.py")

text = train_file.read_text()

text = text.replace(
    "prediction_valid, loss_valid, valid_res = tester.test_classifier(dataset_valid)",
    "valid_metrics, loss_valid, valid_predictions = tester.test_classifier(dataset_valid)"
)

train_file.write_text(text)

print("✅ Validation metrics updated")

✅ Validation metrics updated

In [ ]:
!grep -n "valid_metrics" /content/D-GCAN/DGCAN/train.py

141:        valid_metrics, loss_valid, valid_predictions = tester.test_classifier(dataset_valid)

In [ ]:
from pathlib import Path

train_file = Path("/content/D-GCAN/DGCAN/train.py")

text = train_file.read_text()

old = """        valid_metrics, loss_valid, valid_predictions = tester.test_classifier(dataset_valid)"""

new = """        valid_metrics, loss_valid, valid_predictions = tester.test_classifier(dataset_valid)

        if valid_metrics["auc"] > best_auc:
            best_auc = valid_metrics["auc"]
            tester.save_model(model, file_model)
            print(f"⭐ Best Model Saved | Validation AUC = {best_auc:.4f}")"""

text = text.replace(old, new)

train_file.write_text(text)

print("✅ Best model checkpoint added")

✅ Best model checkpoint added

In [ ]:
!grep -n "Best Model Saved" /content/D-GCAN/DGCAN/train.py

146:            print(f"⭐ Best Model Saved | Validation AUC = {best_auc:.4f}")

In [ ]:
!cp /content/D-GCAN/DGCAN/train_original.py /content/D-GCAN/DGCAN/train.py

print("✅ Original train.py restored")

✅ Original train.py restored

TRAINING STARTS HERE

In [ ]:
import os

EXPERIMENTS = "/content/drive/MyDrive/DGCAN_Project/experiments"

os.makedirs(EXPERIMENTS, exist_ok=True)

print("Created:", EXPERIMENTS)

Created: /content/drive/MyDrive/DGCAN_Project/experiments

In [ ]:
%%writefile /content/drive/MyDrive/DGCAN_Project/experiments/train_bbbp.py

import sys
import os

# Add Original DGCAN to Python path
sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import MolecularGraphNeuralNetwork, Trainer, Tester

import numpy as np
import torch
import timeit

print("Successfully imported Original DGCAN!")

Writing /content/drive/MyDrive/DGCAN_Project/experiments/train_bbbp.py

In [ ]:
!python /content/drive/MyDrive/DGCAN_Project/experiments/train_bbbp.py

Successfully imported Original DGCAN!

In [ ]:
TRAIN = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt"
VALID = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt"
TEST  = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt"

train_dataset = pp.create_dataset(TRAIN, "", "")
valid_dataset = pp.create_dataset(VALID, "", "")
test_dataset  = pp.create_dataset(TEST, "", "")

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))
print("Test :", len(test_dataset))

NameError: name 'pp' is not defined

In [ ]:
%cd /content/D-GCAN/DGCAN

/content/D-GCAN/DGCAN

In [ ]:
import preprocess as pp

In [ ]:
TRAIN = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt"
VALID = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt"
TEST  = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt"

train_dataset = pp.create_dataset(TRAIN, "", "")
valid_dataset = pp.create_dataset(VALID, "", "")
test_dataset  = pp.create_dataset(TEST, "", "")

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))
print("Test :", len(test_dataset))

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train: 1555
Valid: 193
Test : 183

In [ ]:
!cat /content/D-GCAN/DGCAN/run.py

# -*- coding: utf-8 -*-
"""
Created on Thu Apr 28 09:19:10 2022

@author: BM109X32G-10GPU-02
"""
import torch
import pandas as pd
import train
import predict
import numpy as np
import rdkit
from rdkit import Chem
from rdkit.Chem import QED
from rdkit import rdBase, Chem
from rdkit.Chem import PandasTools, QED, Descriptors, rdMolDescriptors
from rdkit.Chem import Lipinski

tes = train.train('../dataset/data_test.txt',
    radius = 1,
    dim = 52,
    layer_hidden = 4,
    layer_output = 10,
    dropout = 0.45,
    batch_train = 8,
    batch_test = 8,
    lr =3e-4,
    lr_decay = 0.85,
    decay_interval = 25,
    iteration = 140,
    N = 5000,
    dataset_train='../dataset/data_train.txt')


test = predict.predict('../dataset/nonUS.txt',
    radius = 1,
    property = True,
    dim = 52 ,
    layer_hidden = 4,
    layer_output = 10,
    dropout = 0.45,
    batch_train = 8,
    batch_test = 8,
    lr = 3e-4,
    lr_decay = 0.85,
    decay_interval = 25 ,
    iteration = 140,
    N = 5000)

In [ ]:
import os

PROJECT_ROOT = "/content/drive/MyDrive/DGCAN_Project"

os.makedirs(f"{PROJECT_ROOT}/utils", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/experiments", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/results", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/models", exist_ok=True)

print("✅ Project folders created!")

✅ Project folders created!

In [ ]:
!ls /content/drive/MyDrive/DGCAN_Project

AUC.txt   dgcan_baseline.pth  models  Phase2  Reports  utils
datasets  experiments	      Phase1  Phase3  results

In [ ]:
%%writefile /content/drive/MyDrive/DGCAN_Project/utils/config.py

CONFIG = {
    # Dataset
    "dataset": "BBBP",

    "train_file": "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt",
    "valid_file": "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt",
    "test_file": "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt",

    # D-GCAN Hyperparameters
    "radius": 1,
    "dim": 52,
    "layer_hidden": 4,
    "layer_output": 10,

    "dropout": 0.45,

    "batch_train": 8,
    "batch_test": 8,

    "lr": 3e-4,
    "lr_decay": 0.85,

    "decay_interval": 25,
    "iteration": 140,

    "N": 5000,

    "seed": 42
}

Writing /content/drive/MyDrive/DGCAN_Project/utils/config.py

In [ ]:
%%writefile /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

import os
import sys
import timeit
import random
import numpy as np
import torch

# -----------------------------
# Add Original DGCAN
# -----------------------------
sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp

from DGCAN import (
    MolecularGraphNeuralNetwork,
    Trainer,
    Tester
)

# -----------------------------
# Load Config
# -----------------------------
sys.path.append("/content/drive/MyDrive/DGCAN_Project/utils")

from config import CONFIG

print("="*60)
print("Cross-Dataset D-GCAN Framework")
print("="*60)

print("Dataset :", CONFIG["dataset"])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device :", device)

Writing /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
!python /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

============================================================
Cross-Dataset D-GCAN Framework
============================================================
Dataset : BBBP
Device : cuda

In [ ]:
print("\nLoading datasets...")

train_dataset = pp.create_dataset(
    CONFIG["train_file"],
    "",
    ""
)

valid_dataset = pp.create_dataset(
    CONFIG["valid_file"],
    "",
    ""
)

test_dataset = pp.create_dataset(
    CONFIG["test_file"],
    "",
    ""
)

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

Loading datasets...

NameError: name 'CONFIG' is not defined

In [ ]:
%%writefile /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

Overwriting /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
import os
import sys
import random
import time
import numpy as np
import torch

# ============================================================
# Add Original D-GCAN to Python Path
# ============================================================

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import MolecularGraphNeuralNetwork, Trainer, Tester

# ============================================================
# Configuration
# ============================================================

CONFIG = {

    "dataset": "BBBP",

    "train_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt",

    "valid_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt",

    "test_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt",

    "radius": 1,
    "dim": 52,
    "layer_hidden": 4,
    "layer_output": 10,

    "dropout": 0.45,

    "batch_train": 8,
    "batch_test": 8,

    "lr": 3e-4,
    "lr_decay": 0.85,

    "decay_interval": 25,

    "iteration": 140,

    "N": 5000,

    "seed": 42,

    "model_path":
    "/content/drive/MyDrive/DGCAN_Project/models/best_model.pth"

}

# ============================================================
# Reproducibility
# ============================================================

random.seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
torch.manual_seed(CONFIG["seed"])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("="*70)
print("Cross Dataset D-GCAN Framework")
print("="*70)

print("Dataset :", CONFIG["dataset"])
print("Device  :", device)

# ============================================================
# Load Dataset
# ============================================================

print("\nLoading datasets...\n")

train_dataset = pp.create_dataset(
    CONFIG["train_file"],
    "",
    ""
)

valid_dataset = pp.create_dataset(
    CONFIG["valid_file"],
    "",
    ""
)

test_dataset = pp.create_dataset(
    CONFIG["test_file"],
    "",
    ""
)

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

# ============================================================
# Build Model
# ============================================================

print("\nCreating D-GCAN...\n")

model = MolecularGraphNeuralNetwork(

    CONFIG["N"],

    CONFIG["dim"],

    CONFIG["layer_hidden"],

    CONFIG["layer_output"],

    CONFIG["dropout"]

).to(device)

trainer = Trainer(

    model,

    CONFIG["lr"],

    CONFIG["batch_train"]

)

tester = Tester(

    model,

    CONFIG["batch_test"]

)

print("Model Created Successfully")

print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

print("="*70)

======================================================================
Cross Dataset D-GCAN Framework
======================================================================
Dataset : BBBP
Device  : cuda

Loading datasets...

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train : 1555
Valid : 193
Test  : 183

Creating D-GCAN...

Model Created Successfully
Parameters: 311698
======================================================================

In [ ]:
!python /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
!grep -n "def train(self" /content/D-GCAN/DGCAN/DGCAN.py

199:    def train(self, dataset):

In [ ]:
!sed -n '199,250p' /content/D-GCAN/DGCAN/DGCAN.py

    def train(self, dataset):
        np.random.shuffle(dataset)
        N = len(dataset)
        loss_total = 0
        SMILES,P, C = '',[], []
        for i in range(0, N, self.batch_train):
            data_batch = list(zip(*dataset[i:i + self.batch_train]))
            Smiles,loss, predicted_scores, correct_labels = self.model.forward_classifier(data_batch, train=True)
            SMILES += ' '.join(Smiles) + ' '
            P.append(predicted_scores)
            C.append(correct_labels)
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            loss_total += loss.item()
        tru = np.concatenate(C)
        pre = np.concatenate(P)
        AUC = roc_auc_score(tru, pre)
        SMILES = SMILES.strip().split()
        pred = [1 if i > 0.15 else 0 for i in pre]
        predictions = np.stack((tru, pred, pre))
        return AUC, loss_total, predictions


class Tester(object):
    def __init__(self, model,batch_test):
        self.model = model
        self.batch_test=batch_test
    def test_classifier(self, dataset):
        N = len(dataset)
        loss_total = 0
        SMILES, P, C = '', [], []
        for i in range(0, N, self.batch_test):
            data_batch = list(zip(*dataset[i:i + self.batch_test]))
            (Smiles, loss, predicted_scores, correct_labels) = self.model.forward_classifier(
                data_batch, train=False)
            SMILES += ' '.join(Smiles) + ' '
            loss_total += loss.item()
            P.append(predicted_scores)
            C.append(correct_labels)
        SMILES = SMILES.strip().split()
        tru = np.concatenate(C)
        pre = np.concatenate(P)
        pred = [1 if i >0.15 else 0 for i in pre]
        AUC = roc_auc_score(tru, pre)
        cnf_matrix=confusion_matrix(tru,pred)
        tn = cnf_matrix[0, 0]
        tp = cnf_matrix[1, 1]
        fn = cnf_matrix[1, 0]
        fp = cnf_matrix[0, 1]
        acc = (tp + tn) / (tp + fp + fn + tn)
        #  Tru=map(str,np.concatenate(C))

In [ ]:
# ============================================================
# Evaluation Function
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    confusion_matrix
)


def evaluate(predictions):
    """
    predictions:
    predictions[0] -> True Labels
    predictions[1] -> Predicted Labels
    predictions[2] -> Prediction Scores
    """

    y_true = predictions[0]
    y_pred = predictions[1]
    y_score = predictions[2]

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred
    ).ravel()

    specificity = tn / (tn + fp)

    metrics = {

        "auc":
        roc_auc_score(y_true, y_score),

        "accuracy":
        accuracy_score(y_true, y_pred),

        "precision":
        precision_score(y_true, y_pred),

        "recall":
        recall_score(y_true, y_pred),

        "f1":
        f1_score(y_true, y_pred),

        "mcc":
        matthews_corrcoef(y_true, y_pred),

        "specificity":
        specificity

    }

    return metrics

In [ ]:
print("\nEvaluation Function Ready!")

Evaluation Function Ready!

In [ ]:
!python /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
# ============================================================
# One Epoch Training Test
# ============================================================

print("\n" + "="*70)
print("Starting One Training Epoch...")
print("="*70)

start_time = time.time()

# -------------------------
# Train
# -------------------------

train_auc, train_loss, train_predictions = trainer.train(train_dataset)

train_metrics = evaluate(train_predictions)

# -------------------------
# Validation
# -------------------------

_, valid_loss, valid_predictions = tester.test_classifier(valid_dataset)

valid_metrics = evaluate(valid_predictions)

elapsed = time.time() - start_time

print("\nEpoch Completed Successfully!")

print("-"*70)

print(f"Train Loss : {train_loss:.4f}")
print(f"Train AUC  : {train_auc:.4f}")

print()

print(f"Valid Loss : {valid_loss:.4f}")
print(f"Valid AUC  : {valid_metrics['auc']:.4f}")
print(f"Valid ACC  : {valid_metrics['accuracy']:.4f}")
print(f"Valid F1   : {valid_metrics['f1']:.4f}")
print(f"Valid MCC  : {valid_metrics['mcc']:.4f}")

print()

print(f"Epoch Time : {elapsed:.2f} sec")

======================================================================
Starting One Training Epoch...
======================================================================

Epoch Completed Successfully!
----------------------------------------------------------------------
Train Loss : 107.7600
Train AUC  : 0.5300

Valid Loss : 19.4568
Valid AUC  : 0.2957
Valid ACC  : 0.5181
Valid F1   : 0.6826
Valid MCC  : 0.0000

Epoch Time : 6.95 sec

In [ ]:
!python /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
with open("/content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py") as f:
    print(len(f.readlines()))

1

In [ ]:
!wc -l /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

0 /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
%%writefile /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

Overwriting /content/drive/MyDrive/DGCAN_Project/experiments/train_dataset.py

In [ ]:
import os
import sys
import time
import random
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix
)

# ==========================================================
# Add Original D-GCAN
# ==========================================================

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import (
    MolecularGraphNeuralNetwork,
    Trainer,
    Tester
)

# ==========================================================
# Configuration
# ==========================================================

CONFIG = {

    # Dataset
    "dataset": "BBBP",

    "train_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt",

    "valid_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt",

    "test_file":
    "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt",

    # Original D-GCAN Hyperparameters
    "radius": 1,

    "dim": 52,

    "layer_hidden": 4,

    "layer_output": 10,

    "dropout": 0.45,

    "batch_train": 8,

    "batch_test": 8,

    "lr": 3e-4,

    "lr_decay": 0.85,

    "decay_interval": 25,

    "iteration": 2,

    "N": 5000,

    # Evaluation

    "threshold": 0.15,

    "seed": 42,

    # Saving

    "model_path":
    "/content/drive/MyDrive/DGCAN_Project/models/best_model.pth",

    "log_path":
    "/content/drive/MyDrive/DGCAN_Project/results/training_log.csv"

}

# ==========================================================
# Reproducibility
# ==========================================================

random.seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
torch.manual_seed(CONFIG["seed"])

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ==========================================================
# Create folders
# ==========================================================

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/models",
    exist_ok=True
)

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/results",
    exist_ok=True
)

# ==========================================================
# Evaluation Function
# ==========================================================

def evaluate(predictions):

    y_true = predictions[0]
    y_pred = predictions[1]
    y_score = predictions[2]

    auc = roc_auc_score(
        y_true,
        y_score
    )

    acc = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    mcc = matthews_corrcoef(
        y_true,
        y_pred
    )

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred
    ).ravel()

    specificity = tn / (tn + fp)

    return {

        "auc": auc,

        "accuracy": acc,

        "precision": precision,

        "recall": recall,

        "f1": f1,

        "mcc": mcc,

        "specificity": specificity

    }


# ==========================================================
# Load Dataset
# ==========================================================

print("="*70)
print("Cross Dataset D-GCAN Framework")
print("="*70)

print("Dataset :", CONFIG["dataset"])
print("Device  :", device)

print("\nLoading Dataset...\n")

train_dataset = pp.create_dataset(
    CONFIG["train_file"],
    "",
    ""
)

valid_dataset = pp.create_dataset(
    CONFIG["valid_file"],
    "",
    ""
)

test_dataset = pp.create_dataset(
    CONFIG["test_file"],
    "",
    ""
)

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

# ==========================================================
# Create Model
# ==========================================================

print("\nCreating Model...\n")

model = MolecularGraphNeuralNetwork(

    CONFIG["N"],

    CONFIG["dim"],

    CONFIG["layer_hidden"],

    CONFIG["layer_output"],

    CONFIG["dropout"]

).to(device)

trainer = Trainer(

    model,

    CONFIG["lr"],

    CONFIG["batch_train"]

)

tester = Tester(

    model,

    CONFIG["batch_test"]

)

print("Model Ready")

print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

print("="*70)

# ==========================================================
# Training Loop
# ==========================================================

history = []

best_auc = -1.0

print("\nStarting Training...\n")

training_start = time.time()

for epoch in range(CONFIG["iteration"]):

    # ------------------------------------------------------
    # Learning Rate Decay
    # ------------------------------------------------------

    if (
        (epoch + 1) % CONFIG["decay_interval"] == 0
    ):

        trainer.optimizer.param_groups[0]["lr"] *= \
            CONFIG["lr_decay"]

    current_lr = trainer.optimizer.param_groups[0]["lr"]

    epoch_start = time.time()

    # ------------------------------------------------------
    # Train
    # ------------------------------------------------------

    train_auc, train_loss, train_predictions = \
        trainer.train(train_dataset)

    train_metrics = evaluate(train_predictions)

    # ------------------------------------------------------
    # Validation
    # ------------------------------------------------------

    _, valid_loss, valid_predictions = \
        tester.test_classifier(valid_dataset)

    valid_metrics = evaluate(valid_predictions)

    epoch_time = time.time() - epoch_start

    # ------------------------------------------------------
    # Save Best Model
    # ------------------------------------------------------

    if valid_metrics["auc"] > best_auc:

        best_auc = valid_metrics["auc"]

        torch.save(
            model.state_dict(),
            CONFIG["model_path"]
        )

        print(
            f"⭐ Best Model Saved "
            f"(Epoch {epoch+1}) "
            f"AUC={best_auc:.4f}"
        )

    # ------------------------------------------------------
    # Store History
    # ------------------------------------------------------

    history.append({

        "epoch": epoch + 1,

        "train_loss": train_loss,

        "valid_loss": valid_loss,

        "train_auc": train_metrics["auc"],

        "valid_auc": valid_metrics["auc"],

        "valid_acc": valid_metrics["accuracy"],

        "valid_precision": valid_metrics["precision"],

        "valid_recall": valid_metrics["recall"],

        "valid_f1": valid_metrics["f1"],

        "valid_mcc": valid_metrics["mcc"],

        "lr": current_lr,

        "epoch_time": epoch_time

    })

    # ------------------------------------------------------
    # Console Output
    # ------------------------------------------------------

    print(

        f"Epoch {epoch+1:03d}/{CONFIG['iteration']} | "

        f"Train AUC: {train_metrics['auc']:.4f} | "

        f"Valid AUC: {valid_metrics['auc']:.4f} | "

        f"Train Loss: {train_loss:.3f} | "

        f"Valid Loss: {valid_loss:.3f}"

    )

# ==========================================================
# Save Training History
# ==========================================================

history_df = pd.DataFrame(history)

history_df.to_csv(

    CONFIG["log_path"],

    index=False

)

training_time = (
    time.time() - training_start
) / 60

print("\nTraining Finished!")

print(
    f"Total Time : {training_time:.2f} minutes"
)

print(
    "Training Log Saved:"
)

print(
    CONFIG["log_path"]
)

print(
    "Best Validation AUC:",
    round(best_auc,4)
)

# ==========================================================
# Load Best Model
# ==========================================================

print("\n" + "=" * 70)
print("Loading Best Model")
print("=" * 70)

if os.path.exists(CONFIG["model_path"]):

    model.load_state_dict(
        torch.load(CONFIG["model_path"], map_location=device)
    )

    print("Best model loaded successfully!")

else:

    raise FileNotFoundError(
        f"Best model not found: {CONFIG['model_path']}"
    )

model.eval()

# ==========================================================
# Final Test Evaluation
# ==========================================================

print("\nRunning Final Test Evaluation...\n")

_, test_loss, test_predictions = tester.test_classifier(test_dataset)

test_metrics = evaluate(test_predictions)

print("=" * 70)
print("FINAL TEST RESULTS")
print("=" * 70)

for metric, value in test_metrics.items():
    print(f"{metric:<15}: {value:.4f}")

print(f"{'test_loss':<15}: {test_loss:.4f}")

# ==========================================================
# Save Test Predictions
# ==========================================================

prediction_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_test_predictions.csv"
)

prediction_df = pd.DataFrame({

    "True_Label": test_predictions[0],

    "Predicted_Label": test_predictions[1],

    "Prediction_Score": test_predictions[2]

})

prediction_df.to_csv(
    prediction_file,
    index=False
)

print("\nPredictions Saved To:")
print(prediction_file)

# ==========================================================
# Save Summary
# ==========================================================

summary = {

    "Dataset": CONFIG["dataset"],

    "Epochs": CONFIG["iteration"],

    "Best Validation AUC": best_auc,

    "Final Test AUC": test_metrics["auc"],

    "Final Test Accuracy": test_metrics["accuracy"],

    "Final Test Precision": test_metrics["precision"],

    "Final Test Recall": test_metrics["recall"],

    "Final Test F1": test_metrics["f1"],

    "Final Test MCC": test_metrics["mcc"],

    "Final Test Specificity": test_metrics["specificity"]

}

summary_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_summary.csv"
)

pd.DataFrame([summary]).to_csv(
    summary_file,
    index=False
)

print("\nSummary Saved To:")
print(summary_file)

print("\n" + "=" * 70)
print("Experiment Completed Successfully!")
print("=" * 70)

======================================================================
Cross Dataset D-GCAN Framework
======================================================================
Dataset : BBBP
Device  : cuda

Loading Dataset...

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train : 1555
Valid : 193
Test  : 183

Creating Model...

Model Ready
Parameters: 311698
======================================================================

Starting Training...

⭐ Best Model Saved (Epoch 1) AUC=0.2957
Epoch 001/2 | Train AUC: 0.5300 | Valid AUC: 0.2957 | Train Loss: 107.760 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 2) AUC=0.3724
Epoch 002/2 | Train AUC: 0.4311 | Valid AUC: 0.3724 | Train Loss: 93.350 | Valid Loss: 19.457

Training Finished!
Total Time : 0.10 minutes
Training Log Saved:
/content/drive/MyDrive/DGCAN_Project/results/training_log.csv
Best Validation AUC: 0.3724

======================================================================
Loading Best Model
======================================================================
Best model loaded successfully!

Running Final Test Evaluation...

======================================================================
FINAL TEST RESULTS
======================================================================
auc            : 0.4662
accuracy       : 0.5137
precision      : 0.5137
recall         : 1.0000
f1             : 0.6787
mcc            : 0.0000
specificity    : 0.0000
test_loss      : 18.3300

Predictions Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_test_predictions.csv

Summary Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_summary.csv

======================================================================
Experiment Completed Successfully!
======================================================================

In [ ]:
import os
import sys
import time
import random
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix
)

# ==========================================================
# Add Original D-GCAN
# ==========================================================

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import (
    MolecularGraphNeuralNetwork,
    Trainer,
    Tester
)

# ==========================================================
# Configuration
# ==========================================================

# ==========================================================
# Dataset Selection
# ==========================================================

DATASET = "BBBP"

BASE_PATH = "/content/drive/MyDrive/DGCAN_Project/datasets/processed"

CONFIG = {

    "dataset": DATASET,

    "train_file":
        f"{BASE_PATH}/{DATASET}_train.txt",

    "valid_file":
        f"{BASE_PATH}/{DATASET}_valid.txt",

    "test_file":
        f"{BASE_PATH}/{DATASET}_test.txt",

    "radius": 1,

    "dim": 52,

    "layer_hidden": 4,

    "layer_output": 10,

    "dropout": 0.45,

    "batch_train": 8,

    "batch_test": 8,

    "lr": 3e-4,

    "lr_decay": 0.85,

    "decay_interval": 25,

    "iteration": 2,

    "N": 5000,

    "threshold": 0.15,

    "seed": 42,

    "model_path":
        f"/content/drive/MyDrive/DGCAN_Project/models/{DATASET}_best_model.pth",

    "log_path":
        f"/content/drive/MyDrive/DGCAN_Project/results/{DATASET}_training_log.csv"

}
# ==========================================================
# Reproducibility
# ==========================================================

random.seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
torch.manual_seed(CONFIG["seed"])

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ==========================================================
# Create folders
# ==========================================================

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/models",
    exist_ok=True
)

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/results",
    exist_ok=True
)

# ==========================================================
# Evaluation Function
# ==========================================================

def evaluate(predictions):

    y_true = predictions[0]
    y_pred = predictions[1]
    y_score = predictions[2]

    auc = roc_auc_score(
        y_true,
        y_score
    )

    acc = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    mcc = matthews_corrcoef(
        y_true,
        y_pred
    )

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred
    ).ravel()

    specificity = tn / (tn + fp)

    return {

        "auc": auc,

        "accuracy": acc,

        "precision": precision,

        "recall": recall,

        "f1": f1,

        "mcc": mcc,

        "specificity": specificity

    }


# ==========================================================
# Load Dataset
# ==========================================================

print("="*70)
print("Cross Dataset D-GCAN Framework")
print("="*70)

print("Dataset :", CONFIG["dataset"])
print("Device  :", device)

print("\nLoading Dataset...\n")

train_dataset = pp.create_dataset(
    CONFIG["train_file"],
    "",
    ""
)

valid_dataset = pp.create_dataset(
    CONFIG["valid_file"],
    "",
    ""
)

test_dataset = pp.create_dataset(
    CONFIG["test_file"],
    "",
    ""
)

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

# ==========================================================
# Create Model
# ==========================================================

print("\nCreating Model...\n")

model = MolecularGraphNeuralNetwork(

    CONFIG["N"],

    CONFIG["dim"],

    CONFIG["layer_hidden"],

    CONFIG["layer_output"],

    CONFIG["dropout"]

).to(device)

trainer = Trainer(

    model,

    CONFIG["lr"],

    CONFIG["batch_train"]

)

tester = Tester(

    model,

    CONFIG["batch_test"]

)

print("Model Ready")

print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

print("="*70)

# ==========================================================
# Training Loop
# ==========================================================

history = []

best_auc = -1.0

print("\nStarting Training...\n")

training_start = time.time()

for epoch in range(CONFIG["iteration"]):

    # ------------------------------------------------------
    # Learning Rate Decay
    # ------------------------------------------------------

    if (
        (epoch + 1) % CONFIG["decay_interval"] == 0
    ):

        trainer.optimizer.param_groups[0]["lr"] *= \
            CONFIG["lr_decay"]

    current_lr = trainer.optimizer.param_groups[0]["lr"]

    epoch_start = time.time()

    # ------------------------------------------------------
    # Train
    # ------------------------------------------------------

    train_auc, train_loss, train_predictions = \
        trainer.train(train_dataset)

    train_metrics = evaluate(train_predictions)

    # ------------------------------------------------------
    # Validation
    # ------------------------------------------------------

    _, valid_loss, valid_predictions = \
        tester.test_classifier(valid_dataset)

    valid_metrics = evaluate(valid_predictions)

    epoch_time = time.time() - epoch_start

    # ------------------------------------------------------
    # Save Best Model
    # ------------------------------------------------------

    if valid_metrics["auc"] > best_auc:

        best_auc = valid_metrics["auc"]

        torch.save(
            model.state_dict(),
            CONFIG["model_path"]
        )

        print(
            f"⭐ Best Model Saved "
            f"(Epoch {epoch+1}) "
            f"AUC={best_auc:.4f}"
        )

    # ------------------------------------------------------
    # Store History
    # ------------------------------------------------------

    history.append({

        "epoch": epoch + 1,

        "train_loss": train_loss,

        "valid_loss": valid_loss,

        "train_auc": train_metrics["auc"],

        "valid_auc": valid_metrics["auc"],

        "valid_acc": valid_metrics["accuracy"],

        "valid_precision": valid_metrics["precision"],

        "valid_recall": valid_metrics["recall"],

        "valid_f1": valid_metrics["f1"],

        "valid_mcc": valid_metrics["mcc"],

        "lr": current_lr,

        "epoch_time": epoch_time

    })

    # ------------------------------------------------------
    # Console Output
    # ------------------------------------------------------

    print(

        f"Epoch {epoch+1:03d}/{CONFIG['iteration']} | "

        f"Train AUC: {train_metrics['auc']:.4f} | "

        f"Valid AUC: {valid_metrics['auc']:.4f} | "

        f"Train Loss: {train_loss:.3f} | "

        f"Valid Loss: {valid_loss:.3f}"

    )

# ==========================================================
# Save Training History
# ==========================================================

history_df = pd.DataFrame(history)

history_df.to_csv(

    CONFIG["log_path"],

    index=False

)

training_time = (
    time.time() - training_start
) / 60

print("\nTraining Finished!")

print(
    f"Total Time : {training_time:.2f} minutes"
)

print(
    "Training Log Saved:"
)

print(
    CONFIG["log_path"]
)

print(
    "Best Validation AUC:",
    round(best_auc,4)
)

# ==========================================================
# Load Best Model
# ==========================================================

print("\n" + "=" * 70)
print("Loading Best Model")
print("=" * 70)

if os.path.exists(CONFIG["model_path"]):

    model.load_state_dict(
        torch.load(CONFIG["model_path"], map_location=device)
    )

    print("Best model loaded successfully!")

else:

    raise FileNotFoundError(
        f"Best model not found: {CONFIG['model_path']}"
    )

model.eval()

# ==========================================================
# Final Test Evaluation
# ==========================================================

print("\nRunning Final Test Evaluation...\n")

_, test_loss, test_predictions = tester.test_classifier(test_dataset)

test_metrics = evaluate(test_predictions)

print("=" * 70)
print("FINAL TEST RESULTS")
print("=" * 70)

for metric, value in test_metrics.items():
    print(f"{metric:<15}: {value:.4f}")

print(f"{'test_loss':<15}: {test_loss:.4f}")

# ==========================================================
# Save Test Predictions
# ==========================================================

prediction_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_test_predictions.csv"
)

prediction_df = pd.DataFrame({

    "True_Label": test_predictions[0],

    "Predicted_Label": test_predictions[1],

    "Prediction_Score": test_predictions[2]

})

prediction_df.to_csv(
    prediction_file,
    index=False
)

print("\nPredictions Saved To:")
print(prediction_file)

# ==========================================================
# Save Summary
# ==========================================================

summary = {

    "Dataset": CONFIG["dataset"],

    "Epochs": CONFIG["iteration"],

    "Best Validation AUC": best_auc,

    "Final Test AUC": test_metrics["auc"],

    "Final Test Accuracy": test_metrics["accuracy"],

    "Final Test Precision": test_metrics["precision"],

    "Final Test Recall": test_metrics["recall"],

    "Final Test F1": test_metrics["f1"],

    "Final Test MCC": test_metrics["mcc"],

    "Final Test Specificity": test_metrics["specificity"]

}

summary_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_summary.csv"
)

pd.DataFrame([summary]).to_csv(
    summary_file,
    index=False
)

print("\nSummary Saved To:")
print(summary_file)

print("\n" + "=" * 70)
print("Experiment Completed Successfully!")
print("=" * 70)

======================================================================
Cross Dataset D-GCAN Framework
======================================================================
Dataset : BBBP
Device  : cuda

Loading Dataset...

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train : 1555
Valid : 193
Test  : 183

Creating Model...

Model Ready
Parameters: 311698
======================================================================

Starting Training...

⭐ Best Model Saved (Epoch 1) AUC=0.2957
Epoch 001/2 | Train AUC: 0.5300 | Valid AUC: 0.2957 | Train Loss: 107.760 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 2) AUC=0.3724
Epoch 002/2 | Train AUC: 0.4311 | Valid AUC: 0.3724 | Train Loss: 93.350 | Valid Loss: 19.457

Training Finished!
Total Time : 0.11 minutes
Training Log Saved:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_training_log.csv
Best Validation AUC: 0.3724

======================================================================
Loading Best Model
======================================================================
Best model loaded successfully!

Running Final Test Evaluation...

======================================================================
FINAL TEST RESULTS
======================================================================
auc            : 0.4662
accuracy       : 0.5137
precision      : 0.5137
recall         : 1.0000
f1             : 0.6787
mcc            : 0.0000
specificity    : 0.0000
test_loss      : 18.3300

Predictions Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_test_predictions.csv

Summary Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_summary.csv

======================================================================
Experiment Completed Successfully!
======================================================================

In [ ]:
import os
import sys
import time
import random
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix
)

# ==========================================================
# Add Original D-GCAN
# ==========================================================

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import (
    MolecularGraphNeuralNetwork,
    Trainer,
    Tester
)

# ==========================================================
# Configuration
# ==========================================================

# ==========================================================
# Dataset Selection
# ==========================================================

DATASET = "BBBP"

BASE_PATH = "/content/drive/MyDrive/DGCAN_Project/datasets/processed"

CONFIG = {

    "dataset": DATASET,

    "train_file":
        f"{BASE_PATH}/{DATASET}_train.txt",

    "valid_file":
        f"{BASE_PATH}/{DATASET}_valid.txt",

    "test_file":
        f"{BASE_PATH}/{DATASET}_test.txt",

    "radius": 1,

    "dim": 52,

    "layer_hidden": 4,

    "layer_output": 10,

    "dropout": 0.45,

    "batch_train": 8,

    "batch_test": 8,

    "lr": 3e-4,

    "lr_decay": 0.85,

    "decay_interval": 25,

    "iteration": 140,

    "N": 5000,

    "threshold": 0.15,

    "seed": 42,

    "model_path":
        f"/content/drive/MyDrive/DGCAN_Project/models/{DATASET}_best_model.pth",

    "log_path":
        f"/content/drive/MyDrive/DGCAN_Project/results/{DATASET}_training_log.csv"

}
# ==========================================================
# Reproducibility
# ==========================================================

random.seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
torch.manual_seed(CONFIG["seed"])

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ==========================================================
# Create folders
# ==========================================================

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/models",
    exist_ok=True
)

os.makedirs(
    "/content/drive/MyDrive/DGCAN_Project/results",
    exist_ok=True
)

# ==========================================================
# Evaluation Function
# ==========================================================

def evaluate(predictions):

    y_true = predictions[0]
    y_pred = predictions[1]
    y_score = predictions[2]

    auc = roc_auc_score(
        y_true,
        y_score
    )

    acc = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    mcc = matthews_corrcoef(
        y_true,
        y_pred
    )

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred
    ).ravel()

    specificity = tn / (tn + fp)

    return {

        "auc": auc,

        "accuracy": acc,

        "precision": precision,

        "recall": recall,

        "f1": f1,

        "mcc": mcc,

        "specificity": specificity

    }


# ==========================================================
# Load Dataset
# ==========================================================

print("="*70)
print("Cross Dataset D-GCAN Framework")
print("="*70)

print("Dataset :", CONFIG["dataset"])
print("Device  :", device)

print("\nLoading Dataset...\n")

train_dataset = pp.create_dataset(
    CONFIG["train_file"],
    "",
    ""
)

valid_dataset = pp.create_dataset(
    CONFIG["valid_file"],
    "",
    ""
)

test_dataset = pp.create_dataset(
    CONFIG["test_file"],
    "",
    ""
)

print("Train :", len(train_dataset))
print("Valid :", len(valid_dataset))
print("Test  :", len(test_dataset))

# ==========================================================
# Create Model
# ==========================================================

print("\nCreating Model...\n")

model = MolecularGraphNeuralNetwork(

    CONFIG["N"],

    CONFIG["dim"],

    CONFIG["layer_hidden"],

    CONFIG["layer_output"],

    CONFIG["dropout"]

).to(device)

trainer = Trainer(

    model,

    CONFIG["lr"],

    CONFIG["batch_train"]

)

tester = Tester(

    model,

    CONFIG["batch_test"]

)

print("Model Ready")

print(
    "Parameters:",
    sum(p.numel() for p in model.parameters())
)

print("="*70)

# ==========================================================
# Training Loop
# ==========================================================

history = []

best_auc = -1.0

print("\nStarting Training...\n")

training_start = time.time()

for epoch in range(CONFIG["iteration"]):

    # ------------------------------------------------------
    # Learning Rate Decay
    # ------------------------------------------------------

    if (
        (epoch + 1) % CONFIG["decay_interval"] == 0
    ):

        trainer.optimizer.param_groups[0]["lr"] *= \
            CONFIG["lr_decay"]

    current_lr = trainer.optimizer.param_groups[0]["lr"]

    epoch_start = time.time()

    # ------------------------------------------------------
    # Train
    # ------------------------------------------------------

    train_auc, train_loss, train_predictions = \
        trainer.train(train_dataset)

    train_metrics = evaluate(train_predictions)

    # ------------------------------------------------------
    # Validation
    # ------------------------------------------------------

    _, valid_loss, valid_predictions = \
        tester.test_classifier(valid_dataset)

    valid_metrics = evaluate(valid_predictions)

    epoch_time = time.time() - epoch_start

    # ------------------------------------------------------
    # Save Best Model
    # ------------------------------------------------------

    if valid_metrics["auc"] > best_auc:

        best_auc = valid_metrics["auc"]

        torch.save(
            model.state_dict(),
            CONFIG["model_path"]
        )

        print(
            f"⭐ Best Model Saved "
            f"(Epoch {epoch+1}) "
            f"AUC={best_auc:.4f}"
        )

    # ------------------------------------------------------
    # Store History
    # ------------------------------------------------------

    history.append({

        "epoch": epoch + 1,

        "train_loss": train_loss,

        "valid_loss": valid_loss,

        "train_auc": train_metrics["auc"],

        "valid_auc": valid_metrics["auc"],

        "valid_acc": valid_metrics["accuracy"],

        "valid_precision": valid_metrics["precision"],

        "valid_recall": valid_metrics["recall"],

        "valid_f1": valid_metrics["f1"],

        "valid_mcc": valid_metrics["mcc"],

        "lr": current_lr,

        "epoch_time": epoch_time

    })

    # ------------------------------------------------------
    # Console Output
    # ------------------------------------------------------

    print(

        f"Epoch {epoch+1:03d}/{CONFIG['iteration']} | "

        f"Train AUC: {train_metrics['auc']:.4f} | "

        f"Valid AUC: {valid_metrics['auc']:.4f} | "

        f"Train Loss: {train_loss:.3f} | "

        f"Valid Loss: {valid_loss:.3f}"

    )

# ==========================================================
# Save Training History
# ==========================================================

history_df = pd.DataFrame(history)

history_df.to_csv(

    CONFIG["log_path"],

    index=False

)

training_time = (
    time.time() - training_start
) / 60

print("\nTraining Finished!")

print(
    f"Total Time : {training_time:.2f} minutes"
)

print(
    "Training Log Saved:"
)

print(
    CONFIG["log_path"]
)

print(
    "Best Validation AUC:",
    round(best_auc,4)
)

# ==========================================================
# Load Best Model
# ==========================================================

print("\n" + "=" * 70)
print("Loading Best Model")
print("=" * 70)

if os.path.exists(CONFIG["model_path"]):

    model.load_state_dict(
        torch.load(CONFIG["model_path"], map_location=device)
    )

    print("Best model loaded successfully!")

else:

    raise FileNotFoundError(
        f"Best model not found: {CONFIG['model_path']}"
    )

model.eval()

# ==========================================================
# Final Test Evaluation
# ==========================================================

print("\nRunning Final Test Evaluation...\n")

_, test_loss, test_predictions = tester.test_classifier(test_dataset)

test_metrics = evaluate(test_predictions)

print("=" * 70)
print("FINAL TEST RESULTS")
print("=" * 70)

for metric, value in test_metrics.items():
    print(f"{metric:<15}: {value:.4f}")

print(f"{'test_loss':<15}: {test_loss:.4f}")

# ==========================================================
# Save Test Predictions
# ==========================================================

prediction_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_test_predictions.csv"
)

prediction_df = pd.DataFrame({

    "True_Label": test_predictions[0],

    "Predicted_Label": test_predictions[1],

    "Prediction_Score": test_predictions[2]

})

prediction_df.to_csv(
    prediction_file,
    index=False
)

print("\nPredictions Saved To:")
print(prediction_file)

# ==========================================================
# Save Summary
# ==========================================================

summary = {

    "Dataset": CONFIG["dataset"],

    "Epochs": CONFIG["iteration"],

    "Best Validation AUC": best_auc,

    "Final Test AUC": test_metrics["auc"],

    "Final Test Accuracy": test_metrics["accuracy"],

    "Final Test Precision": test_metrics["precision"],

    "Final Test Recall": test_metrics["recall"],

    "Final Test F1": test_metrics["f1"],

    "Final Test MCC": test_metrics["mcc"],

    "Final Test Specificity": test_metrics["specificity"]

}

summary_file = (
    f"/content/drive/MyDrive/DGCAN_Project/results/"
    f"{CONFIG['dataset']}_summary.csv"
)

pd.DataFrame([summary]).to_csv(
    summary_file,
    index=False
)

print("\nSummary Saved To:")
print(summary_file)

print("\n" + "=" * 70)
print("Experiment Completed Successfully!")
print("=" * 70)

======================================================================
Cross Dataset D-GCAN Framework
======================================================================
Dataset : BBBP
Device  : cuda

Loading Dataset...

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train : 1555
Valid : 193
Test  : 183

Creating Model...

Model Ready
Parameters: 311698
======================================================================

Starting Training...

⭐ Best Model Saved (Epoch 1) AUC=0.2957
Epoch 001/140 | Train AUC: 0.5300 | Valid AUC: 0.2957 | Train Loss: 107.760 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 2) AUC=0.3724
Epoch 002/140 | Train AUC: 0.4311 | Valid AUC: 0.3724 | Train Loss: 93.350 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 3) AUC=0.4400
Epoch 003/140 | Train AUC: 0.4744 | Valid AUC: 0.4400 | Train Loss: 93.340 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 4) AUC=0.4850
Epoch 004/140 | Train AUC: 0.4855 | Valid AUC: 0.4850 | Train Loss: 93.337 | Valid Loss: 19.457
⭐ Best Model Saved (Epoch 5) AUC=0.5000
Epoch 005/140 | Train AUC: 0.4820 | Valid AUC: 0.5000 | Train Loss: 93.337 | Valid Loss: 19.457
Epoch 006/140 | Train AUC: 0.4819 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 007/140 | Train AUC: 0.4846 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 008/140 | Train AUC: 0.4857 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 009/140 | Train AUC: 0.4877 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 010/140 | Train AUC: 0.4907 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 011/140 | Train AUC: 0.4907 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 012/140 | Train AUC: 0.4927 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 013/140 | Train AUC: 0.4915 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 014/140 | Train AUC: 0.4950 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 015/140 | Train AUC: 0.4961 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 016/140 | Train AUC: 0.4958 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 017/140 | Train AUC: 0.4965 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 018/140 | Train AUC: 0.4958 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 019/140 | Train AUC: 0.4969 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 020/140 | Train AUC: 0.4969 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 021/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 022/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 023/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 024/140 | Train AUC: 0.4977 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 025/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 026/140 | Train AUC: 0.4981 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 027/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 028/140 | Train AUC: 0.4981 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 029/140 | Train AUC: 0.4977 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 030/140 | Train AUC: 0.4973 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 031/140 | Train AUC: 0.4988 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 032/140 | Train AUC: 0.4981 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 033/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 034/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 035/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 036/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 037/140 | Train AUC: 0.4977 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 038/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 039/140 | Train AUC: 0.4992 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 040/140 | Train AUC: 0.4985 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 041/140 | Train AUC: 0.4992 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 042/140 | Train AUC: 0.4992 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 043/140 | Train AUC: 0.4988 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 044/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 045/140 | Train AUC: 0.4992 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 046/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 047/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 048/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 049/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 050/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 051/140 | Train AUC: 0.4992 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 052/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 053/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 054/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 055/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 056/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 057/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 058/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 059/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 060/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 061/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 062/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 063/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 064/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 065/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 066/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 067/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 068/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 069/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 070/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 071/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 072/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 073/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 074/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 075/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 076/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 077/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 078/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 079/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 080/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 081/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 082/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 083/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 084/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 085/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 086/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 087/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 088/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 089/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 090/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 091/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 092/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 093/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 094/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 095/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 096/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 097/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 098/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 099/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 100/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 101/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 102/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 103/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 104/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 105/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 106/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 107/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 108/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 109/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 110/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 111/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 112/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 113/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 114/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 115/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 116/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 117/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 118/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 119/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 120/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 121/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 122/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 123/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 124/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 125/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 126/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 127/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 128/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 129/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 130/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 131/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 132/140 | Train AUC: 0.4996 | Valid AUC: 0.5000 | Train Loss: 93.753 | Valid Loss: 19.457
Epoch 133/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 134/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 135/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 136/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 137/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 138/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.544 | Valid Loss: 19.457
Epoch 139/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457
Epoch 140/140 | Train AUC: 0.5000 | Valid AUC: 0.5000 | Train Loss: 93.336 | Valid Loss: 19.457

Training Finished!
Total Time : 7.36 minutes
Training Log Saved:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_training_log.csv
Best Validation AUC: 0.5

======================================================================
Loading Best Model
======================================================================
Best model loaded successfully!

Running Final Test Evaluation...

======================================================================
FINAL TEST RESULTS
======================================================================
auc            : 0.4953
accuracy       : 0.5137
precision      : 0.5137
recall         : 1.0000
f1             : 0.6787
mcc            : 0.0000
specificity    : 0.0000
test_loss      : 18.3300

Predictions Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_test_predictions.csv

Summary Saved To:
/content/drive/MyDrive/DGCAN_Project/results/BBBP_summary.csv

======================================================================
Experiment Completed Successfully!
======================================================================

In [1]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!git clone https://github.com/JinYSun/D-GCAN.git

fatal: destination path 'D-GCAN' already exists and is not an empty directory.

In [4]:
!pip install rdkit-pypi

Requirement already satisfied: rdkit-pypi in /usr/local/lib/python3.11/dist-packages (2022.9.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rdkit-pypi) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from rdkit-pypi) (11.2.1)

In [5]:
import sys

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
import train
from DGCAN import MolecularGraphNeuralNetwork, Trainer, Tester

print("Everything imported successfully!")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-5-2788943968.py", line 5, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/usr/local/lib/python3.11/dist-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-5-2788943968.py", line 5, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 20, in <module>
    from rdkit.Chem import rdchem

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-5-2788943968.py", line 5, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 24, in <module>
    from rdkit.Chem.rdmolops import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-5-2788943968.py", line 5, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 20, in <module>
    from rdkit.Chem import rdDepictor

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-5-2788943968.py", line 5, in <cell line: 0>
    import preprocess as pp
  File "/content/D-GCAN/DGCAN/preprocess.py", line 11, in <module>
    from rdkit import Chem
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 21, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D

AttributeError: _ARRAY_API not found

Everything imported successfully!

In [ ]:
TRAIN = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt"

train_dataset = pp.create_dataset(TRAIN, "", "")

print(len(train_dataset))

In [1]:
TRAIN = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt"
VALID = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt"
TEST  = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt"

train_dataset = pp.create_dataset(TRAIN, "", "")
valid_dataset = pp.create_dataset(VALID, "", "")
test_dataset  = pp.create_dataset(TEST, "", "")

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))
print("Test :", len(test_dataset))

NameError: name 'pp' is not defined

In [2]:
import numpy as np
print(np.__version__)

2.0.2

In [3]:
import rdkit
print(rdkit.__version__)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-3-2699164797.py", line 1, in <cell line: 0>
    import rdkit
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/usr/local/lib/python3.11/dist-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-3-2699164797.py", line 1, in <cell line: 0>
    import rdkit
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 20, in <module>
    from rdkit.Chem import rdchem

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-3-2699164797.py", line 1, in <cell line: 0>
    import rdkit
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/__init__.py", line 24, in <module>
    from rdkit.Chem.rdmolops import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-3-2699164797.py", line 1, in <cell line: 0>
    import rdkit
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 20, in <module>
    from rdkit.Chem import rdDepictor

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipython-input-3-2699164797.py", line 1, in <cell line: 0>
    import rdkit
  File "/usr/local/lib/python3.11/dist-packages/rdkit/__init__.py", line 23, in <module>
    from rdkit.Chem.Draw import IPythonConsole
  File "/usr/local/lib/python3.11/dist-packages/rdkit/Chem/Draw/__init__.py", line 21, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D

AttributeError: _ARRAY_API not found

2022.09.5

In [1]:
!pip uninstall -y numpy rdkit rdkit-pypi

Found existing installation: numpy 2.0.2
Uninstalling numpy-2.0.2:
  Successfully uninstalled numpy-2.0.2
WARNING: Skipping rdkit as it is not installed.
WARNING: Skipping rdkit-pypi as it is not installed.

In [1]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.11/dist-packages (1.26.4)

In [2]:
!pip install rdkit-pypi==2022.9.5

Collecting rdkit-pypi==2022.9.5
  Downloading rdkit_pypi-2022.9.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rdkit-pypi==2022.9.5) (1.26.4)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from rdkit-pypi==2022.9.5) (11.2.1)
Downloading rdkit_pypi-2022.9.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 66.6 MB/s eta 0:00:00
Installing collected packages: rdkit-pypi
Successfully installed rdkit-pypi-2022.9.5

In [ ]:
import os
os.kill(os.getpid(), 9)

In [1]:
import numpy as np
print(np.__version__)

1.26.4

In [2]:
from rdkit import Chem

print("RDKit Imported Successfully")

RDKit Imported Successfully

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!git clone https://github.com/JinYSun/D-GCAN.git

Cloning into 'D-GCAN'...
remote: Enumerating objects: 493, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 493 (delta 31), reused 30 (delta 14), pack-reused 441 (from 1)
Receiving objects: 100% (493/493), 7.53 MiB | 13.87 MiB/s, done.
Resolving deltas: 100% (278/278), done.

In [6]:
!ls /content/D-GCAN

dataset  Discussion  README.md	solgan.png  Tutorial.ipynb
DGCAN	 LICENSE     screening	Test

In [7]:
import sys

sys.path.append("/content/D-GCAN/DGCAN")

import preprocess as pp
from DGCAN import MolecularGraphNeuralNetwork, Trainer, Tester

print("Imports Successful!")

ModuleNotFoundError: No module named 'preprocess'

In [8]:
!ls -R /content/D-GCAN | head -50

/content/D-GCAN:
dataset
DGCAN
Discussion
LICENSE
README.md
screening
solgan.png
Test
Tutorial.ipynb

/content/D-GCAN/dataset:
bRo5.txt
data_test.txt
data_train.txt
nonUS.txt
withdrawn.txt

/content/D-GCAN/DGCAN:
DGCAN.py
dict
__init__.py
predict.py
preprocess.py
results
run.py
train.py
Tutorial.ipynb

/content/D-GCAN/DGCAN/dict:
-atom_dict.pickle
-bond_dict.pickle
-edge_dict.pickle
-fingerprint_dict.pickle

/content/D-GCAN/DGCAN/results:
AUC.txt

/content/D-GCAN/Discussion:
CNN.py
GNN.py
GPC.py
preprocess.py
RF.py
svc.py

/content/D-GCAN/screening:
ADMET.ipynb
COVIDVS-3.ipynb
Dataset

In [9]:
import sys

sys.path.insert(0, "/content/D-GCAN/DGCAN")

import preprocess

print("SUCCESS")

ModuleNotFoundError: No module named 'preprocess'

In [10]:
import os

print(os.path.exists("/content/D-GCAN/DGCAN/preprocess.py"))
print(os.path.isfile("/content/D-GCAN/DGCAN/preprocess.py"))

True
True

In [11]:
import os

print(os.listdir("/content/D-GCAN/DGCAN"))

['preprocess.py', '__init__.py', 'dict', 'results', 'predict.py', 'run.py', 'Tutorial.ipynb', 'DGCAN.py', 'train.py']

In [12]:
import traceback
import importlib.util

path = "/content/D-GCAN/DGCAN/preprocess.py"

try:
    spec = importlib.util.spec_from_file_location("preprocess", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    print("SUCCESS")
except Exception as e:
    traceback.print_exc()

SUCCESS

In [14]:
import importlib.util

spec = importlib.util.spec_from_file_location(
    "preprocess",
    "/content/D-GCAN/DGCAN/preprocess.py"
)

pp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pp)

print("preprocess loaded!")

preprocess loaded!

In [15]:
TRAIN = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt"

train_dataset = pp.create_dataset(TRAIN, "", "")

print(len(train_dataset))

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt
1555

In [16]:
VALID = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt"
TEST  = "/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt"

valid_dataset = pp.create_dataset(VALID, "", "")
test_dataset  = pp.create_dataset(TEST, "", "")

print("Train:", len(train_dataset))
print("Valid:", len(valid_dataset))
print("Test :", len(test_dataset))

/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_valid.txt
/content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_test.txt
Train: 1555
Valid: 193
Test : 183

In [17]:
from collections import Counter

def count_labels(dataset, name):
    labels = [sample[4].item() for sample in dataset]
    counter = Counter(labels)
    total = len(labels)

    print(f"\n{name}")
    print("-"*40)

    for label in sorted(counter):
        print(f"Label {label}: {counter[label]} ({counter[label]/total:.2%})")

count_labels(train_dataset, "TRAIN")
count_labels(valid_dataset, "VALID")
count_labels(test_dataset, "TEST")

TRAIN
----------------------------------------
Label 0: 258 (16.59%)
Label 1: 1297 (83.41%)

VALID
----------------------------------------
Label 0: 93 (48.19%)
Label 1: 100 (51.81%)

TEST
----------------------------------------
Label 0: 89 (48.63%)
Label 1: 94 (51.37%)

In [19]:
import pandas as pd

RAW = "/content/drive/MyDrive/DGCAN_Project/datasets/raw"

df = pd.read_csv(f"{RAW}/BBBP.csv")

print(df.shape)
df.head()

(2050, 4)

,num,name,p_np,smiles
0,1,Propanolol,1,[Cl].CC(C)NCC(O)COc1cccc2ccccc12
1,2,Terbutylchlorambucil,1,C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl
2,3,40730,1,c12c3c(N4CCN(C)CC4)c(F)cc1c(c(C(O)=O)cn2C(C)CO...
3,4,24,1,C1CCN(CC1)Cc1cccc(c1)OCCCNC(=O)C
4,5,cloxacillin,1,Cc1onc(c2ccccc2Cl)c1C(=O)N[C@H]3[C@H]4SC(C)(C)...

In [20]:
df = df[["smiles", "p_np"]]

df = df.dropna()

df = df.drop_duplicates(subset=["smiles"])

df = df[~df["smiles"].str.contains(r"\.")]

df["p_np"] = df["p_np"].astype(int)

print(df.shape)

(1945, 2)

In [21]:
print(df["p_np"].value_counts())
print()
print(df["p_np"].value_counts(normalize=True))

p_np
1    1501
0     444
Name: count, dtype: int64

p_np
1    0.771722
0    0.228278
Name: proportion, dtype: float64

In [22]:
!head -5 /content/D-GCAN/dataset/data_train.txt

CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@H](CCC(O)=O)NC(=O)[C@H](CC1=CC=CC=C1)NC(=O)[C@H](CC(O)=O)NC(=O)CNC(=O)[C@H](CC(N)=O)NC(=O)CNC(=O)CNC(=O)CNC(=O)CNC(=O)[C@@H]1CCCN1C(=O)[C@H](CCCNC(N)=N)NC(=O)[C@@H]1CCCN1C(=O)[C@H](N)CC1=CC=CC=C1)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CCC(O)=O)C(=O)N[C@@H](CC1=CC=C(O)C=C1)C(=O)N[C@@H](CC(C)C)C(O)=O  1
CCCCCCCN(CC)CCCC(O)C1=CC=C(NS(C)(=O)=O)C=C1  1
CC[C@H]1[C@@H](CC2=CN=CN2C)COC1=O  1
CN(C)S(=O)(=O)C1=CC2=C(SC3=CC=CC=C3\C2=C\CCN2CCN(C)CC2)C=C1  1
CC(=O)NO  1

In [23]:
!head -5 /content/drive/MyDrive/DGCAN_Project/datasets/processed/BBBP_train.txt

C(=O)(OC(C)(C)C)CCCc1ccc(cc1)N(CCCl)CCCl	1
C[C@H](N)Cc1ccccc1	1
C[S](=O)(=O)c1ccc(cc1)[C@@H](O)[C@@H](CO)NC(=O)C(Cl)Cl	1
CC(N)COc1c(C)cccc1C	1
c1(ccccc1)CC	1

In [24]:
import torch

MODEL_PATH = "/content/drive/MyDrive/DGCAN_Project/models/BBBP_best_model.pth"

print(torch.load(MODEL_PATH, map_location="cpu").keys())

odict_keys(['embed_fingerprint.weight', 'W_fingerprint.0.weight', 'W_fingerprint.0.bias', 'W_fingerprint.1.weight', 'W_fingerprint.1.bias', 'W_fingerprint.2.weight', 'W_fingerprint.2.bias', 'W_fingerprint.3.weight', 'W_fingerprint.3.bias', 'W_output.0.weight', 'W_output.0.bias', 'W_output.1.weight', 'W_output.1.bias', 'W_output.2.weight', 'W_output.2.bias', 'W_output.3.weight', 'W_output.3.bias', 'W_output.4.weight', 'W_output.4.bias', 'W_output.5.weight', 'W_output.5.bias', 'W_output.6.weight', 'W_output.6.bias', 'W_output.7.weight', 'W_output.7.bias', 'W_output.8.weight', 'W_output.8.bias', 'W_output.9.weight', 'W_output.9.bias', 'W_property.weight', 'W_property.bias', 'attentions.attention_0.W', 'attentions.attention_0.a', 'attentions.attention_1.W', 'attentions.attention_1.a', 'attentions.out_att.W', 'attentions.out_att.a'])

In [25]:
model = MolecularGraphNeuralNetwork(
    N=5000,
    dim=52,
    layer_hidden=4,
    layer_output=10,
    dropout=0.45
)

model.load_state_dict(torch.load(MODEL_PATH, map_location="cpu"))
model.eval()

print("Model Loaded Successfully")

NameError: name 'MolecularGraphNeuralNetwork' is not defined

In [26]:
!find /content/D-GCAN -maxdepth 2 -type f

/content/D-GCAN/Discussion/GPC.py
/content/D-GCAN/Discussion/preprocess.py
/content/D-GCAN/Discussion/GNN.py
/content/D-GCAN/Discussion/RF.py
/content/D-GCAN/Discussion/svc.py
/content/D-GCAN/Discussion/CNN.py
/content/D-GCAN/solgan.png
/content/D-GCAN/.git/HEAD
/content/D-GCAN/.git/index
/content/D-GCAN/.git/config
/content/D-GCAN/.git/packed-refs
/content/D-GCAN/.git/description
/content/D-GCAN/LICENSE
/content/D-GCAN/.gitignore
/content/D-GCAN/Tutorial.ipynb
/content/D-GCAN/DGCAN/preprocess.py
/content/D-GCAN/DGCAN/__init__.py
/content/D-GCAN/DGCAN/predict.py
/content/D-GCAN/DGCAN/run.py
/content/D-GCAN/DGCAN/Tutorial.ipynb
/content/D-GCAN/DGCAN/DGCAN.py
/content/D-GCAN/DGCAN/train.py
/content/D-GCAN/Test/test.ipynb
/content/D-GCAN/README.md
/content/D-GCAN/dataset/bRo5.txt
/content/D-GCAN/dataset/nonUS.txt
/content/D-GCAN/dataset/data_train.txt
/content/D-GCAN/dataset/data_test.txt
/content/D-GCAN/dataset/withdrawn.txt
/content/D-GCAN/screening/DTI.ipynb
/content/D-GCAN/screening/process.png
/content/D-GCAN/screening/ADMET.ipynb
/content/D-GCAN/screening/README.md
/content/D-GCAN/screening/COVIDVS-3.ipynb